package com.ecommerce.OnlineShopping.mapper;

import com.ecommerce.OnlineShopping.domain.AccountLinked;
import com.ecommerce.OnlineShopping.domain.AccountLinkedExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AccountLinkedMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accountlinked
     *
     * @mbg.generated Mon May 25 10:16:08 NPT 2020
     */
    long countByExample(AccountLinkedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accountlinked
     *
     * @mbg.generated Mon May 25 10:16:08 NPT 2020
     */
    int deleteByExample(AccountLinkedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accountlinked
     *
     * @mbg.generated Mon May 25 10:16:08 NPT 2020
     */
    int deleteByPrimaryKey(Long acclinkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accountlinked
     *
     * @mbg.generated Mon May 25 10:16:08 NPT 2020
     */
    int insert(AccountLinked record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accountlinked
     *
     * @mbg.generated Mon May 25 10:16:08 NPT 2020
     */
    int insertSelective(AccountLinked record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accountlinked
     *
     * @mbg.generated Mon May 25 10:16:08 NPT 2020
     */
    List<AccountLinked> selectByExample(AccountLinkedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accountlinked
     *
     * @mbg.generated Mon May 25 10:16:08 NPT 2020
     */
    AccountLinked selectByPrimaryKey(Long acclinkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accountlinked
     *
     * @mbg.generated Mon May 25 10:16:08 NPT 2020
     */
    int updateByExampleSelective(@Param("record") AccountLinked record, @Param("example") AccountLinkedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accountlinked
     *
     * @mbg.generated Mon May 25 10:16:08 NPT 2020
     */
    int updateByExample(@Param("record") AccountLinked record, @Param("example") AccountLinkedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accountlinked
     *
     * @mbg.generated Mon May 25 10:16:08 NPT 2020
     */
    int updateByPrimaryKeySelective(AccountLinked record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accountlinked
     *
     * @mbg.generated Mon May 25 10:16:08 NPT 2020
     */
    int updateByPrimaryKey(AccountLinked record);
}