package com.ecommerce.OnlineShopping.mapper;

import com.ecommerce.OnlineShopping.domain.BankDetails;
import com.ecommerce.OnlineShopping.domain.BankDetailsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BankDetailsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bankdetails
     *
     * @mbg.generated Mon May 25 10:16:09 NPT 2020
     */
    long countByExample(BankDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bankdetails
     *
     * @mbg.generated Mon May 25 10:16:09 NPT 2020
     */
    int deleteByExample(BankDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bankdetails
     *
     * @mbg.generated Mon May 25 10:16:09 NPT 2020
     */
    int deleteByPrimaryKey(Long bankdetailsid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bankdetails
     *
     * @mbg.generated Mon May 25 10:16:09 NPT 2020
     */
    int insert(BankDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bankdetails
     *
     * @mbg.generated Mon May 25 10:16:09 NPT 2020
     */
    int insertSelective(BankDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bankdetails
     *
     * @mbg.generated Mon May 25 10:16:09 NPT 2020
     */
    List<BankDetails> selectByExample(BankDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bankdetails
     *
     * @mbg.generated Mon May 25 10:16:09 NPT 2020
     */
    BankDetails selectByPrimaryKey(Long bankdetailsid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bankdetails
     *
     * @mbg.generated Mon May 25 10:16:09 NPT 2020
     */
    int updateByExampleSelective(@Param("record") BankDetails record, @Param("example") BankDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bankdetails
     *
     * @mbg.generated Mon May 25 10:16:09 NPT 2020
     */
    int updateByExample(@Param("record") BankDetails record, @Param("example") BankDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bankdetails
     *
     * @mbg.generated Mon May 25 10:16:09 NPT 2020
     */
    int updateByPrimaryKeySelective(BankDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bankdetails
     *
     * @mbg.generated Mon May 25 10:16:09 NPT 2020
     */
    int updateByPrimaryKey(BankDetails record);
}