package com.ecommerce.OnlineShopping.mapper;

import com.ecommerce.OnlineShopping.domain.OrderDetails;
import com.ecommerce.OnlineShopping.domain.OrderDetailsExample;

import java.math.BigDecimal;
import java.util.List;

import com.ecommerce.OnlineShopping.domain.ShoppingCart;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

public interface OrderDetailsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetails
     *
     * @mbg.generated Thu Jun 04 14:27:37 NPT 2020
     */
    long countByExample(OrderDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetails
     *
     * @mbg.generated Thu Jun 04 14:27:37 NPT 2020
     */
    int deleteByExample(OrderDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetails
     *
     * @mbg.generated Thu Jun 04 14:27:37 NPT 2020
     */
    int deleteByPrimaryKey(Long oderdetailsid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetails
     *
     * @mbg.generated Thu Jun 04 14:27:37 NPT 2020
     */
    int insert(OrderDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetails
     *
     * @mbg.generated Thu Jun 04 14:27:37 NPT 2020
     */
    int insertSelective(OrderDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetails
     *
     * @mbg.generated Thu Jun 04 14:27:37 NPT 2020
     */
    List<OrderDetails> selectByExample(OrderDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetails
     *
     * @mbg.generated Thu Jun 04 14:27:37 NPT 2020
     */
    OrderDetails selectByPrimaryKey(Long oderdetailsid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetails
     *
     * @mbg.generated Thu Jun 04 14:27:37 NPT 2020
     */
    int updateByExampleSelective(@Param("record") OrderDetails record, @Param("example") OrderDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetails
     *
     * @mbg.generated Thu Jun 04 14:27:37 NPT 2020
     */
    int updateByExample(@Param("record") OrderDetails record, @Param("example") OrderDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetails
     *
     * @mbg.generated Thu Jun 04 14:27:37 NPT 2020
     */
    int updateByPrimaryKeySelective(OrderDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetails
     *
     * @mbg.generated Thu Jun 04 14:27:37 NPT 2020
     */
    int updateByPrimaryKey(OrderDetails record);

    @Select("SELECT SUM(prodPrice) AS TotalPrice FROM OrderDetails WHERE username = #{username}")
    BigDecimal totalSum(@Param("username") String username);

    @Select("DELETE FROM OrderDetails WHERE prodId=#{prodId}")
    ShoppingCart removeFromOrders(@Param("prodId") Long id);
}