package com.ecommerce.OnlineShopping.mapper;

import com.ecommerce.OnlineShopping.domain.Rating;
import com.ecommerce.OnlineShopping.domain.RatingExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RatingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rating
     *
     * @mbg.generated Mon May 25 10:16:09 NPT 2020
     */
    long countByExample(RatingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rating
     *
     * @mbg.generated Mon May 25 10:16:09 NPT 2020
     */
    int deleteByExample(RatingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rating
     *
     * @mbg.generated Mon May 25 10:16:09 NPT 2020
     */
    int deleteByPrimaryKey(Long ratingsid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rating
     *
     * @mbg.generated Mon May 25 10:16:09 NPT 2020
     */
    int insert(Rating record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rating
     *
     * @mbg.generated Mon May 25 10:16:09 NPT 2020
     */
    int insertSelective(Rating record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rating
     *
     * @mbg.generated Mon May 25 10:16:09 NPT 2020
     */
    List<Rating> selectByExample(RatingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rating
     *
     * @mbg.generated Mon May 25 10:16:09 NPT 2020
     */
    Rating selectByPrimaryKey(Long ratingsid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rating
     *
     * @mbg.generated Mon May 25 10:16:09 NPT 2020
     */
    int updateByExampleSelective(@Param("record") Rating record, @Param("example") RatingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rating
     *
     * @mbg.generated Mon May 25 10:16:09 NPT 2020
     */
    int updateByExample(@Param("record") Rating record, @Param("example") RatingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rating
     *
     * @mbg.generated Mon May 25 10:16:09 NPT 2020
     */
    int updateByPrimaryKeySelective(Rating record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rating
     *
     * @mbg.generated Mon May 25 10:16:09 NPT 2020
     */
    int updateByPrimaryKey(Rating record);
}