package com.ecommerce.OnlineShopping.mapper;

import com.ecommerce.OnlineShopping.domain.ShippingDetails;
import com.ecommerce.OnlineShopping.domain.ShippingDetailsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShippingDetailsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shippingdetails
     *
     * @mbg.generated Mon May 25 10:16:09 NPT 2020
     */
    long countByExample(ShippingDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shippingdetails
     *
     * @mbg.generated Mon May 25 10:16:09 NPT 2020
     */
    int deleteByExample(ShippingDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shippingdetails
     *
     * @mbg.generated Mon May 25 10:16:09 NPT 2020
     */
    int deleteByPrimaryKey(Long shpid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shippingdetails
     *
     * @mbg.generated Mon May 25 10:16:09 NPT 2020
     */
    int insert(ShippingDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shippingdetails
     *
     * @mbg.generated Mon May 25 10:16:09 NPT 2020
     */
    int insertSelective(ShippingDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shippingdetails
     *
     * @mbg.generated Mon May 25 10:16:09 NPT 2020
     */
    List<ShippingDetails> selectByExample(ShippingDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shippingdetails
     *
     * @mbg.generated Mon May 25 10:16:09 NPT 2020
     */
    ShippingDetails selectByPrimaryKey(Long shpid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shippingdetails
     *
     * @mbg.generated Mon May 25 10:16:09 NPT 2020
     */
    int updateByExampleSelective(@Param("record") ShippingDetails record, @Param("example") ShippingDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shippingdetails
     *
     * @mbg.generated Mon May 25 10:16:09 NPT 2020
     */
    int updateByExample(@Param("record") ShippingDetails record, @Param("example") ShippingDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shippingdetails
     *
     * @mbg.generated Mon May 25 10:16:09 NPT 2020
     */
    int updateByPrimaryKeySelective(ShippingDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shippingdetails
     *
     * @mbg.generated Mon May 25 10:16:09 NPT 2020
     */
    int updateByPrimaryKey(ShippingDetails record);
}