package com.ecommerce.OnlineShopping.mapper;

import com.ecommerce.OnlineShopping.domain.TopSales;
import com.ecommerce.OnlineShopping.domain.TopSalesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TopSalesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topsales
     *
     * @mbg.generated Mon Jun 01 15:18:33 NPT 2020
     */
    long countByExample(TopSalesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topsales
     *
     * @mbg.generated Mon Jun 01 15:18:33 NPT 2020
     */
    int deleteByExample(TopSalesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topsales
     *
     * @mbg.generated Mon Jun 01 15:18:33 NPT 2020
     */
    int deleteByPrimaryKey(Long salesid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topsales
     *
     * @mbg.generated Mon Jun 01 15:18:33 NPT 2020
     */
    int insert(TopSales record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topsales
     *
     * @mbg.generated Mon Jun 01 15:18:33 NPT 2020
     */
    int insertSelective(TopSales record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topsales
     *
     * @mbg.generated Mon Jun 01 15:18:33 NPT 2020
     */
    List<TopSales> selectByExampleWithBLOBs(TopSalesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topsales
     *
     * @mbg.generated Mon Jun 01 15:18:33 NPT 2020
     */
    List<TopSales> selectByExample(TopSalesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topsales
     *
     * @mbg.generated Mon Jun 01 15:18:33 NPT 2020
     */
    TopSales selectByPrimaryKey(Long salesid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topsales
     *
     * @mbg.generated Mon Jun 01 15:18:33 NPT 2020
     */
    int updateByExampleSelective(@Param("record") TopSales record, @Param("example") TopSalesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topsales
     *
     * @mbg.generated Mon Jun 01 15:18:33 NPT 2020
     */
    int updateByExampleWithBLOBs(@Param("record") TopSales record, @Param("example") TopSalesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topsales
     *
     * @mbg.generated Mon Jun 01 15:18:33 NPT 2020
     */
    int updateByExample(@Param("record") TopSales record, @Param("example") TopSalesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topsales
     *
     * @mbg.generated Mon Jun 01 15:18:33 NPT 2020
     */
    int updateByPrimaryKeySelective(TopSales record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topsales
     *
     * @mbg.generated Mon Jun 01 15:18:33 NPT 2020
     */
    int updateByPrimaryKeyWithBLOBs(TopSales record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topsales
     *
     * @mbg.generated Mon Jun 01 15:18:33 NPT 2020
     */
    int updateByPrimaryKey(TopSales record);
}