package com.ecommerce.OnlineShopping.mapper;

import com.ecommerce.OnlineShopping.domain.ShoppingCart;
import com.ecommerce.OnlineShopping.domain.WishList;
import com.ecommerce.OnlineShopping.domain.WishListExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

public interface WishListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wishlist
     *
     * @mbg.generated Tue Jun 02 00:27:09 NPT 2020
     */
    long countByExample(WishListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wishlist
     *
     * @mbg.generated Tue Jun 02 00:27:09 NPT 2020
     */
    int deleteByExample(WishListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wishlist
     *
     * @mbg.generated Tue Jun 02 00:27:09 NPT 2020
     */
    int deleteByPrimaryKey(Long wishlistid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wishlist
     *
     * @mbg.generated Tue Jun 02 00:27:09 NPT 2020
     */
    int insert(WishList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wishlist
     *
     * @mbg.generated Tue Jun 02 00:27:09 NPT 2020
     */
    int insertSelective(WishList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wishlist
     *
     * @mbg.generated Tue Jun 02 00:27:09 NPT 2020
     */
    List<WishList> selectByExample(WishListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wishlist
     *
     * @mbg.generated Tue Jun 02 00:27:09 NPT 2020
     */
    WishList selectByPrimaryKey(Long wishlistid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wishlist
     *
     * @mbg.generated Tue Jun 02 00:27:09 NPT 2020
     */
    int updateByExampleSelective(@Param("record") WishList record, @Param("example") WishListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wishlist
     *
     * @mbg.generated Tue Jun 02 00:27:09 NPT 2020
     */
    int updateByExample(@Param("record") WishList record, @Param("example") WishListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wishlist
     *
     * @mbg.generated Tue Jun 02 00:27:09 NPT 2020
     */
    int updateByPrimaryKeySelective(WishList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wishlist
     *
     * @mbg.generated Tue Jun 02 00:27:09 NPT 2020
     */
    int updateByPrimaryKey(WishList record);

    @Select("Select * from WishList wl LEFT JOIN Product p ON p.prodid = wl.prodid WHERE username = #{username}")
    List<WishList> productInfo(@Param("username") String username, @Param("prodid") Integer pid);

    WishList getWishListByUsername(@Param("username") String username);

    @Select("DELETE FROM WishList WHERE prodId=#{prodId}")
    WishList removeFromWishList(@Param("prodId") Long id);

}