package com.ecommerce.OnlineShopping.domain;

public class Admin {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.uname
     *
     * @mbg.generated Mon May 25 10:16:09 NPT 2020
     */
    private String uname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.Pword
     *
     * @mbg.generated Mon May 25 10:16:09 NPT 2020
     */
    private String pword;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.uname
     *
     * @return the value of admin.uname
     *
     * @mbg.generated Mon May 25 10:16:09 NPT 2020
     */
    public String getUname() {
        return uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.uname
     *
     * @param uname the value for admin.uname
     *
     * @mbg.generated Mon May 25 10:16:09 NPT 2020
     */
    public void setUname(String uname) {
        this.uname = uname == null ? null : uname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.Pword
     *
     * @return the value of admin.Pword
     *
     * @mbg.generated Mon May 25 10:16:09 NPT 2020
     */
    public String getPword() {
        return pword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.Pword
     *
     * @param pword the value for admin.Pword
     *
     * @mbg.generated Mon May 25 10:16:09 NPT 2020
     */
    public void setPword(String pword) {
        this.pword = pword == null ? null : pword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbg.generated Mon May 25 10:16:09 NPT 2020
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Admin other = (Admin) that;
        return (this.getUname() == null ? other.getUname() == null : this.getUname().equals(other.getUname()))
            && (this.getPword() == null ? other.getPword() == null : this.getPword().equals(other.getPword()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbg.generated Mon May 25 10:16:09 NPT 2020
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getUname() == null) ? 0 : getUname().hashCode());
        result = prime * result + ((getPword() == null) ? 0 : getPword().hashCode());
        return result;
    }
}