package com.ecommerce.OnlineShopping.domain;

public class BankDetails {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bankdetails.BankDetailsID
     *
     * @mbg.generated Mon May 25 10:16:09 NPT 2020
     */
    private Long bankdetailsid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bankdetails.CardNo
     *
     * @mbg.generated Mon May 25 10:16:09 NPT 2020
     */
    private String cardno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bankdetails.PinCode
     *
     * @mbg.generated Mon May 25 10:16:09 NPT 2020
     */
    private String pincode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bankdetails.accLinkID
     *
     * @mbg.generated Mon May 25 10:16:09 NPT 2020
     */
    private Long acclinkid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bankdetails.BankDetailsID
     *
     * @return the value of bankdetails.BankDetailsID
     *
     * @mbg.generated Mon May 25 10:16:09 NPT 2020
     */
    public Long getBankdetailsid() {
        return bankdetailsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bankdetails.BankDetailsID
     *
     * @param bankdetailsid the value for bankdetails.BankDetailsID
     *
     * @mbg.generated Mon May 25 10:16:09 NPT 2020
     */
    public void setBankdetailsid(Long bankdetailsid) {
        this.bankdetailsid = bankdetailsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bankdetails.CardNo
     *
     * @return the value of bankdetails.CardNo
     *
     * @mbg.generated Mon May 25 10:16:09 NPT 2020
     */
    public String getCardno() {
        return cardno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bankdetails.CardNo
     *
     * @param cardno the value for bankdetails.CardNo
     *
     * @mbg.generated Mon May 25 10:16:09 NPT 2020
     */
    public void setCardno(String cardno) {
        this.cardno = cardno == null ? null : cardno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bankdetails.PinCode
     *
     * @return the value of bankdetails.PinCode
     *
     * @mbg.generated Mon May 25 10:16:09 NPT 2020
     */
    public String getPincode() {
        return pincode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bankdetails.PinCode
     *
     * @param pincode the value for bankdetails.PinCode
     *
     * @mbg.generated Mon May 25 10:16:09 NPT 2020
     */
    public void setPincode(String pincode) {
        this.pincode = pincode == null ? null : pincode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bankdetails.accLinkID
     *
     * @return the value of bankdetails.accLinkID
     *
     * @mbg.generated Mon May 25 10:16:09 NPT 2020
     */
    public Long getAcclinkid() {
        return acclinkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bankdetails.accLinkID
     *
     * @param acclinkid the value for bankdetails.accLinkID
     *
     * @mbg.generated Mon May 25 10:16:09 NPT 2020
     */
    public void setAcclinkid(Long acclinkid) {
        this.acclinkid = acclinkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bankdetails
     *
     * @mbg.generated Mon May 25 10:16:09 NPT 2020
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        BankDetails other = (BankDetails) that;
        return (this.getBankdetailsid() == null ? other.getBankdetailsid() == null : this.getBankdetailsid().equals(other.getBankdetailsid()))
            && (this.getCardno() == null ? other.getCardno() == null : this.getCardno().equals(other.getCardno()))
            && (this.getPincode() == null ? other.getPincode() == null : this.getPincode().equals(other.getPincode()))
            && (this.getAcclinkid() == null ? other.getAcclinkid() == null : this.getAcclinkid().equals(other.getAcclinkid()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bankdetails
     *
     * @mbg.generated Mon May 25 10:16:09 NPT 2020
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getBankdetailsid() == null) ? 0 : getBankdetailsid().hashCode());
        result = prime * result + ((getCardno() == null) ? 0 : getCardno().hashCode());
        result = prime * result + ((getPincode() == null) ? 0 : getPincode().hashCode());
        result = prime * result + ((getAcclinkid() == null) ? 0 : getAcclinkid().hashCode());
        return result;
    }
}