package com.ecommerce.OnlineShopping.domain;

public class Message {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.msgID
     *
     * @mbg.generated Fri Jun 05 15:17:41 NPT 2020
     */
    private Long msgid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.username
     *
     * @mbg.generated Fri Jun 05 15:17:41 NPT 2020
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.Name
     *
     * @mbg.generated Fri Jun 05 15:17:41 NPT 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.subject
     *
     * @mbg.generated Fri Jun 05 15:17:41 NPT 2020
     */
    private String subject;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.email
     *
     * @mbg.generated Fri Jun 05 15:17:41 NPT 2020
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.message
     *
     * @mbg.generated Fri Jun 05 15:17:41 NPT 2020
     */
    private String message;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.msgID
     *
     * @return the value of message.msgID
     *
     * @mbg.generated Fri Jun 05 15:17:41 NPT 2020
     */
    public Long getMsgid() {
        return msgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.msgID
     *
     * @param msgid the value for message.msgID
     *
     * @mbg.generated Fri Jun 05 15:17:41 NPT 2020
     */
    public void setMsgid(Long msgid) {
        this.msgid = msgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.username
     *
     * @return the value of message.username
     *
     * @mbg.generated Fri Jun 05 15:17:41 NPT 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.username
     *
     * @param username the value for message.username
     *
     * @mbg.generated Fri Jun 05 15:17:41 NPT 2020
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.Name
     *
     * @return the value of message.Name
     *
     * @mbg.generated Fri Jun 05 15:17:41 NPT 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.Name
     *
     * @param name the value for message.Name
     *
     * @mbg.generated Fri Jun 05 15:17:41 NPT 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.subject
     *
     * @return the value of message.subject
     *
     * @mbg.generated Fri Jun 05 15:17:41 NPT 2020
     */
    public String getSubject() {
        return subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.subject
     *
     * @param subject the value for message.subject
     *
     * @mbg.generated Fri Jun 05 15:17:41 NPT 2020
     */
    public void setSubject(String subject) {
        this.subject = subject == null ? null : subject.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.email
     *
     * @return the value of message.email
     *
     * @mbg.generated Fri Jun 05 15:17:41 NPT 2020
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.email
     *
     * @param email the value for message.email
     *
     * @mbg.generated Fri Jun 05 15:17:41 NPT 2020
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.message
     *
     * @return the value of message.message
     *
     * @mbg.generated Fri Jun 05 15:17:41 NPT 2020
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.message
     *
     * @param message the value for message.message
     *
     * @mbg.generated Fri Jun 05 15:17:41 NPT 2020
     */
    public void setMessage(String message) {
        this.message = message == null ? null : message.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated Fri Jun 05 15:17:41 NPT 2020
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Message other = (Message) that;
        return (this.getMsgid() == null ? other.getMsgid() == null : this.getMsgid().equals(other.getMsgid()))
            && (this.getUsername() == null ? other.getUsername() == null : this.getUsername().equals(other.getUsername()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getSubject() == null ? other.getSubject() == null : this.getSubject().equals(other.getSubject()))
            && (this.getEmail() == null ? other.getEmail() == null : this.getEmail().equals(other.getEmail()))
            && (this.getMessage() == null ? other.getMessage() == null : this.getMessage().equals(other.getMessage()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated Fri Jun 05 15:17:41 NPT 2020
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getMsgid() == null) ? 0 : getMsgid().hashCode());
        result = prime * result + ((getUsername() == null) ? 0 : getUsername().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getSubject() == null) ? 0 : getSubject().hashCode());
        result = prime * result + ((getEmail() == null) ? 0 : getEmail().hashCode());
        result = prime * result + ((getMessage() == null) ? 0 : getMessage().hashCode());
        return result;
    }
}