package com.ecommerce.OnlineShopping.domain;

import java.math.BigDecimal;
import java.util.Date;

public class Orders {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.ordID
     *
     * @mbg.generated Thu Jun 04 12:39:36 NPT 2020
     */
    private Long ordid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.oderDetailsID
     *
     * @mbg.generated Thu Jun 04 12:39:36 NPT 2020
     */
    private Long oderdetailsid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.shpID
     *
     * @mbg.generated Thu Jun 04 12:39:36 NPT 2020
     */
    private String shpid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.username
     *
     * @mbg.generated Thu Jun 04 12:39:36 NPT 2020
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.odTime
     *
     * @mbg.generated Thu Jun 04 12:39:36 NPT 2020
     */
    private Date odtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.odDate
     *
     * @mbg.generated Thu Jun 04 12:39:36 NPT 2020
     */
    private Date oddate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.ShpAmt
     *
     * @mbg.generated Thu Jun 04 12:39:36 NPT 2020
     */
    private BigDecimal shpamt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.ProdAmt
     *
     * @mbg.generated Thu Jun 04 12:39:36 NPT 2020
     */
    private BigDecimal prodamt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.shpAddress
     *
     * @mbg.generated Thu Jun 04 12:39:36 NPT 2020
     */
    private String shpaddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.phoneNum
     *
     * @mbg.generated Thu Jun 04 12:39:36 NPT 2020
     */
    private String phonenum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.ordID
     *
     * @return the value of orders.ordID
     *
     * @mbg.generated Thu Jun 04 12:39:36 NPT 2020
     */
    public Long getOrdid() {
        return ordid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.ordID
     *
     * @param ordid the value for orders.ordID
     *
     * @mbg.generated Thu Jun 04 12:39:36 NPT 2020
     */
    public void setOrdid(Long ordid) {
        this.ordid = ordid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.oderDetailsID
     *
     * @return the value of orders.oderDetailsID
     *
     * @mbg.generated Thu Jun 04 12:39:36 NPT 2020
     */
    public Long getOderdetailsid() {
        return oderdetailsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.oderDetailsID
     *
     * @param oderdetailsid the value for orders.oderDetailsID
     *
     * @mbg.generated Thu Jun 04 12:39:36 NPT 2020
     */
    public void setOderdetailsid(Long oderdetailsid) {
        this.oderdetailsid = oderdetailsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.shpID
     *
     * @return the value of orders.shpID
     *
     * @mbg.generated Thu Jun 04 12:39:36 NPT 2020
     */
    public String getShpid() {
        return shpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.shpID
     *
     * @param shpid the value for orders.shpID
     *
     * @mbg.generated Thu Jun 04 12:39:36 NPT 2020
     */
    public void setShpid(String shpid) {
        this.shpid = shpid == null ? null : shpid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.username
     *
     * @return the value of orders.username
     *
     * @mbg.generated Thu Jun 04 12:39:36 NPT 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.username
     *
     * @param username the value for orders.username
     *
     * @mbg.generated Thu Jun 04 12:39:36 NPT 2020
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.odTime
     *
     * @return the value of orders.odTime
     *
     * @mbg.generated Thu Jun 04 12:39:36 NPT 2020
     */
    public Date getOdtime() {
        return odtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.odTime
     *
     * @param odtime the value for orders.odTime
     *
     * @mbg.generated Thu Jun 04 12:39:36 NPT 2020
     */
    public void setOdtime(Date odtime) {
        this.odtime = odtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.odDate
     *
     * @return the value of orders.odDate
     *
     * @mbg.generated Thu Jun 04 12:39:36 NPT 2020
     */
    public Date getOddate() {
        return oddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.odDate
     *
     * @param oddate the value for orders.odDate
     *
     * @mbg.generated Thu Jun 04 12:39:36 NPT 2020
     */
    public void setOddate(Date oddate) {
        this.oddate = oddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.ShpAmt
     *
     * @return the value of orders.ShpAmt
     *
     * @mbg.generated Thu Jun 04 12:39:36 NPT 2020
     */
    public BigDecimal getShpamt() {
        return shpamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.ShpAmt
     *
     * @param shpamt the value for orders.ShpAmt
     *
     * @mbg.generated Thu Jun 04 12:39:36 NPT 2020
     */
    public void setShpamt(BigDecimal shpamt) {
        this.shpamt = shpamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.ProdAmt
     *
     * @return the value of orders.ProdAmt
     *
     * @mbg.generated Thu Jun 04 12:39:36 NPT 2020
     */
    public BigDecimal getProdamt() {
        return prodamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.ProdAmt
     *
     * @param prodamt the value for orders.ProdAmt
     *
     * @mbg.generated Thu Jun 04 12:39:36 NPT 2020
     */
    public void setProdamt(BigDecimal prodamt) {
        this.prodamt = prodamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.shpAddress
     *
     * @return the value of orders.shpAddress
     *
     * @mbg.generated Thu Jun 04 12:39:36 NPT 2020
     */
    public String getShpaddress() {
        return shpaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.shpAddress
     *
     * @param shpaddress the value for orders.shpAddress
     *
     * @mbg.generated Thu Jun 04 12:39:36 NPT 2020
     */
    public void setShpaddress(String shpaddress) {
        this.shpaddress = shpaddress == null ? null : shpaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.phoneNum
     *
     * @return the value of orders.phoneNum
     *
     * @mbg.generated Thu Jun 04 12:39:36 NPT 2020
     */
    public String getPhonenum() {
        return phonenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.phoneNum
     *
     * @param phonenum the value for orders.phoneNum
     *
     * @mbg.generated Thu Jun 04 12:39:36 NPT 2020
     */
    public void setPhonenum(String phonenum) {
        this.phonenum = phonenum == null ? null : phonenum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Thu Jun 04 12:39:36 NPT 2020
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Orders other = (Orders) that;
        return (this.getOrdid() == null ? other.getOrdid() == null : this.getOrdid().equals(other.getOrdid()))
            && (this.getOderdetailsid() == null ? other.getOderdetailsid() == null : this.getOderdetailsid().equals(other.getOderdetailsid()))
            && (this.getShpid() == null ? other.getShpid() == null : this.getShpid().equals(other.getShpid()))
            && (this.getUsername() == null ? other.getUsername() == null : this.getUsername().equals(other.getUsername()))
            && (this.getOdtime() == null ? other.getOdtime() == null : this.getOdtime().equals(other.getOdtime()))
            && (this.getOddate() == null ? other.getOddate() == null : this.getOddate().equals(other.getOddate()))
            && (this.getShpamt() == null ? other.getShpamt() == null : this.getShpamt().equals(other.getShpamt()))
            && (this.getProdamt() == null ? other.getProdamt() == null : this.getProdamt().equals(other.getProdamt()))
            && (this.getShpaddress() == null ? other.getShpaddress() == null : this.getShpaddress().equals(other.getShpaddress()))
            && (this.getPhonenum() == null ? other.getPhonenum() == null : this.getPhonenum().equals(other.getPhonenum()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Thu Jun 04 12:39:36 NPT 2020
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getOrdid() == null) ? 0 : getOrdid().hashCode());
        result = prime * result + ((getOderdetailsid() == null) ? 0 : getOderdetailsid().hashCode());
        result = prime * result + ((getShpid() == null) ? 0 : getShpid().hashCode());
        result = prime * result + ((getUsername() == null) ? 0 : getUsername().hashCode());
        result = prime * result + ((getOdtime() == null) ? 0 : getOdtime().hashCode());
        result = prime * result + ((getOddate() == null) ? 0 : getOddate().hashCode());
        result = prime * result + ((getShpamt() == null) ? 0 : getShpamt().hashCode());
        result = prime * result + ((getProdamt() == null) ? 0 : getProdamt().hashCode());
        result = prime * result + ((getShpaddress() == null) ? 0 : getShpaddress().hashCode());
        result = prime * result + ((getPhonenum() == null) ? 0 : getPhonenum().hashCode());
        return result;
    }
}