package com.ecommerce.OnlineShopping.domain;

import java.math.BigDecimal;

public class OrderDetails {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderdetails.oderDetailsID
     *
     * @mbg.generated Thu Jun 04 14:27:37 NPT 2020
     */
    private Long oderdetailsid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderdetails.quant
     *
     * @mbg.generated Thu Jun 04 14:27:37 NPT 2020
     */
    private Long quant;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderdetails.totalAmt
     *
     * @mbg.generated Thu Jun 04 14:27:37 NPT 2020
     */
    private BigDecimal totalamt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderdetails.ordID
     *
     * @mbg.generated Thu Jun 04 14:27:37 NPT 2020
     */
    private Long ordid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderdetails.prodID
     *
     * @mbg.generated Thu Jun 04 14:27:37 NPT 2020
     */
    private Long prodid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderdetails.prodPrice
     *
     * @mbg.generated Thu Jun 04 14:27:37 NPT 2020
     */
    private BigDecimal prodprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderdetails.username
     *
     * @mbg.generated Thu Jun 04 14:27:37 NPT 2020
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderdetails.cartID
     *
     * @mbg.generated Thu Jun 04 14:27:37 NPT 2020
     */
    private Long cartid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderdetails.shpAddress
     *
     * @mbg.generated Thu Jun 04 14:27:37 NPT 2020
     */
    private String shpaddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderdetails.phoneNum
     *
     * @mbg.generated Thu Jun 04 14:27:37 NPT 2020
     */
    private String phonenum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderdetails.oderDetailsID
     *
     * @return the value of orderdetails.oderDetailsID
     *
     * @mbg.generated Thu Jun 04 14:27:37 NPT 2020
     */
    public Long getOderdetailsid() {
        return oderdetailsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderdetails.oderDetailsID
     *
     * @param oderdetailsid the value for orderdetails.oderDetailsID
     *
     * @mbg.generated Thu Jun 04 14:27:37 NPT 2020
     */
    public void setOderdetailsid(Long oderdetailsid) {
        this.oderdetailsid = oderdetailsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderdetails.quant
     *
     * @return the value of orderdetails.quant
     *
     * @mbg.generated Thu Jun 04 14:27:37 NPT 2020
     */
    public Long getQuant() {
        return quant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderdetails.quant
     *
     * @param quant the value for orderdetails.quant
     *
     * @mbg.generated Thu Jun 04 14:27:37 NPT 2020
     */
    public void setQuant(Long quant) {
        this.quant = quant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderdetails.totalAmt
     *
     * @return the value of orderdetails.totalAmt
     *
     * @mbg.generated Thu Jun 04 14:27:37 NPT 2020
     */
    public BigDecimal getTotalamt() {
        return totalamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderdetails.totalAmt
     *
     * @param totalamt the value for orderdetails.totalAmt
     *
     * @mbg.generated Thu Jun 04 14:27:37 NPT 2020
     */
    public void setTotalamt(BigDecimal totalamt) {
        this.totalamt = totalamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderdetails.ordID
     *
     * @return the value of orderdetails.ordID
     *
     * @mbg.generated Thu Jun 04 14:27:37 NPT 2020
     */
    public Long getOrdid() {
        return ordid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderdetails.ordID
     *
     * @param ordid the value for orderdetails.ordID
     *
     * @mbg.generated Thu Jun 04 14:27:37 NPT 2020
     */
    public void setOrdid(Long ordid) {
        this.ordid = ordid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderdetails.prodID
     *
     * @return the value of orderdetails.prodID
     *
     * @mbg.generated Thu Jun 04 14:27:37 NPT 2020
     */
    public Long getProdid() {
        return prodid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderdetails.prodID
     *
     * @param prodid the value for orderdetails.prodID
     *
     * @mbg.generated Thu Jun 04 14:27:37 NPT 2020
     */
    public void setProdid(Long prodid) {
        this.prodid = prodid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderdetails.prodPrice
     *
     * @return the value of orderdetails.prodPrice
     *
     * @mbg.generated Thu Jun 04 14:27:37 NPT 2020
     */
    public BigDecimal getProdprice() {
        return prodprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderdetails.prodPrice
     *
     * @param prodprice the value for orderdetails.prodPrice
     *
     * @mbg.generated Thu Jun 04 14:27:37 NPT 2020
     */
    public void setProdprice(BigDecimal prodprice) {
        this.prodprice = prodprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderdetails.username
     *
     * @return the value of orderdetails.username
     *
     * @mbg.generated Thu Jun 04 14:27:37 NPT 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderdetails.username
     *
     * @param username the value for orderdetails.username
     *
     * @mbg.generated Thu Jun 04 14:27:37 NPT 2020
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderdetails.cartID
     *
     * @return the value of orderdetails.cartID
     *
     * @mbg.generated Thu Jun 04 14:27:37 NPT 2020
     */
    public Long getCartid() {
        return cartid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderdetails.cartID
     *
     * @param cartid the value for orderdetails.cartID
     *
     * @mbg.generated Thu Jun 04 14:27:37 NPT 2020
     */
    public void setCartid(Long cartid) {
        this.cartid = cartid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderdetails.shpAddress
     *
     * @return the value of orderdetails.shpAddress
     *
     * @mbg.generated Thu Jun 04 14:27:37 NPT 2020
     */
    public String getShpaddress() {
        return shpaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderdetails.shpAddress
     *
     * @param shpaddress the value for orderdetails.shpAddress
     *
     * @mbg.generated Thu Jun 04 14:27:37 NPT 2020
     */
    public void setShpaddress(String shpaddress) {
        this.shpaddress = shpaddress == null ? null : shpaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderdetails.phoneNum
     *
     * @return the value of orderdetails.phoneNum
     *
     * @mbg.generated Thu Jun 04 14:27:37 NPT 2020
     */
    public String getPhonenum() {
        return phonenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderdetails.phoneNum
     *
     * @param phonenum the value for orderdetails.phoneNum
     *
     * @mbg.generated Thu Jun 04 14:27:37 NPT 2020
     */
    public void setPhonenum(String phonenum) {
        this.phonenum = phonenum == null ? null : phonenum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetails
     *
     * @mbg.generated Thu Jun 04 14:27:37 NPT 2020
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        OrderDetails other = (OrderDetails) that;
        return (this.getOderdetailsid() == null ? other.getOderdetailsid() == null : this.getOderdetailsid().equals(other.getOderdetailsid()))
            && (this.getQuant() == null ? other.getQuant() == null : this.getQuant().equals(other.getQuant()))
            && (this.getTotalamt() == null ? other.getTotalamt() == null : this.getTotalamt().equals(other.getTotalamt()))
            && (this.getOrdid() == null ? other.getOrdid() == null : this.getOrdid().equals(other.getOrdid()))
            && (this.getProdid() == null ? other.getProdid() == null : this.getProdid().equals(other.getProdid()))
            && (this.getProdprice() == null ? other.getProdprice() == null : this.getProdprice().equals(other.getProdprice()))
            && (this.getUsername() == null ? other.getUsername() == null : this.getUsername().equals(other.getUsername()))
            && (this.getCartid() == null ? other.getCartid() == null : this.getCartid().equals(other.getCartid()))
            && (this.getShpaddress() == null ? other.getShpaddress() == null : this.getShpaddress().equals(other.getShpaddress()))
            && (this.getPhonenum() == null ? other.getPhonenum() == null : this.getPhonenum().equals(other.getPhonenum()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetails
     *
     * @mbg.generated Thu Jun 04 14:27:37 NPT 2020
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getOderdetailsid() == null) ? 0 : getOderdetailsid().hashCode());
        result = prime * result + ((getQuant() == null) ? 0 : getQuant().hashCode());
        result = prime * result + ((getTotalamt() == null) ? 0 : getTotalamt().hashCode());
        result = prime * result + ((getOrdid() == null) ? 0 : getOrdid().hashCode());
        result = prime * result + ((getProdid() == null) ? 0 : getProdid().hashCode());
        result = prime * result + ((getProdprice() == null) ? 0 : getProdprice().hashCode());
        result = prime * result + ((getUsername() == null) ? 0 : getUsername().hashCode());
        result = prime * result + ((getCartid() == null) ? 0 : getCartid().hashCode());
        result = prime * result + ((getShpaddress() == null) ? 0 : getShpaddress().hashCode());
        result = prime * result + ((getPhonenum() == null) ? 0 : getPhonenum().hashCode());
        return result;
    }
}