package com.ecommerce.OnlineShopping.domain;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class OrderDetailsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table orderdetails
     *
     * @mbg.generated Thu Jun 04 14:27:37 NPT 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table orderdetails
     *
     * @mbg.generated Thu Jun 04 14:27:37 NPT 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table orderdetails
     *
     * @mbg.generated Thu Jun 04 14:27:37 NPT 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetails
     *
     * @mbg.generated Thu Jun 04 14:27:37 NPT 2020
     */
    public OrderDetailsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetails
     *
     * @mbg.generated Thu Jun 04 14:27:37 NPT 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetails
     *
     * @mbg.generated Thu Jun 04 14:27:37 NPT 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetails
     *
     * @mbg.generated Thu Jun 04 14:27:37 NPT 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetails
     *
     * @mbg.generated Thu Jun 04 14:27:37 NPT 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetails
     *
     * @mbg.generated Thu Jun 04 14:27:37 NPT 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetails
     *
     * @mbg.generated Thu Jun 04 14:27:37 NPT 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetails
     *
     * @mbg.generated Thu Jun 04 14:27:37 NPT 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetails
     *
     * @mbg.generated Thu Jun 04 14:27:37 NPT 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetails
     *
     * @mbg.generated Thu Jun 04 14:27:37 NPT 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetails
     *
     * @mbg.generated Thu Jun 04 14:27:37 NPT 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table orderdetails
     *
     * @mbg.generated Thu Jun 04 14:27:37 NPT 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andOderdetailsidIsNull() {
            addCriterion("oderDetailsID is null");
            return (Criteria) this;
        }

        public Criteria andOderdetailsidIsNotNull() {
            addCriterion("oderDetailsID is not null");
            return (Criteria) this;
        }

        public Criteria andOderdetailsidEqualTo(Long value) {
            addCriterion("oderDetailsID =", value, "oderdetailsid");
            return (Criteria) this;
        }

        public Criteria andOderdetailsidNotEqualTo(Long value) {
            addCriterion("oderDetailsID <>", value, "oderdetailsid");
            return (Criteria) this;
        }

        public Criteria andOderdetailsidGreaterThan(Long value) {
            addCriterion("oderDetailsID >", value, "oderdetailsid");
            return (Criteria) this;
        }

        public Criteria andOderdetailsidGreaterThanOrEqualTo(Long value) {
            addCriterion("oderDetailsID >=", value, "oderdetailsid");
            return (Criteria) this;
        }

        public Criteria andOderdetailsidLessThan(Long value) {
            addCriterion("oderDetailsID <", value, "oderdetailsid");
            return (Criteria) this;
        }

        public Criteria andOderdetailsidLessThanOrEqualTo(Long value) {
            addCriterion("oderDetailsID <=", value, "oderdetailsid");
            return (Criteria) this;
        }

        public Criteria andOderdetailsidIn(List<Long> values) {
            addCriterion("oderDetailsID in", values, "oderdetailsid");
            return (Criteria) this;
        }

        public Criteria andOderdetailsidNotIn(List<Long> values) {
            addCriterion("oderDetailsID not in", values, "oderdetailsid");
            return (Criteria) this;
        }

        public Criteria andOderdetailsidBetween(Long value1, Long value2) {
            addCriterion("oderDetailsID between", value1, value2, "oderdetailsid");
            return (Criteria) this;
        }

        public Criteria andOderdetailsidNotBetween(Long value1, Long value2) {
            addCriterion("oderDetailsID not between", value1, value2, "oderdetailsid");
            return (Criteria) this;
        }

        public Criteria andQuantIsNull() {
            addCriterion("quant is null");
            return (Criteria) this;
        }

        public Criteria andQuantIsNotNull() {
            addCriterion("quant is not null");
            return (Criteria) this;
        }

        public Criteria andQuantEqualTo(Long value) {
            addCriterion("quant =", value, "quant");
            return (Criteria) this;
        }

        public Criteria andQuantNotEqualTo(Long value) {
            addCriterion("quant <>", value, "quant");
            return (Criteria) this;
        }

        public Criteria andQuantGreaterThan(Long value) {
            addCriterion("quant >", value, "quant");
            return (Criteria) this;
        }

        public Criteria andQuantGreaterThanOrEqualTo(Long value) {
            addCriterion("quant >=", value, "quant");
            return (Criteria) this;
        }

        public Criteria andQuantLessThan(Long value) {
            addCriterion("quant <", value, "quant");
            return (Criteria) this;
        }

        public Criteria andQuantLessThanOrEqualTo(Long value) {
            addCriterion("quant <=", value, "quant");
            return (Criteria) this;
        }

        public Criteria andQuantIn(List<Long> values) {
            addCriterion("quant in", values, "quant");
            return (Criteria) this;
        }

        public Criteria andQuantNotIn(List<Long> values) {
            addCriterion("quant not in", values, "quant");
            return (Criteria) this;
        }

        public Criteria andQuantBetween(Long value1, Long value2) {
            addCriterion("quant between", value1, value2, "quant");
            return (Criteria) this;
        }

        public Criteria andQuantNotBetween(Long value1, Long value2) {
            addCriterion("quant not between", value1, value2, "quant");
            return (Criteria) this;
        }

        public Criteria andTotalamtIsNull() {
            addCriterion("totalAmt is null");
            return (Criteria) this;
        }

        public Criteria andTotalamtIsNotNull() {
            addCriterion("totalAmt is not null");
            return (Criteria) this;
        }

        public Criteria andTotalamtEqualTo(BigDecimal value) {
            addCriterion("totalAmt =", value, "totalamt");
            return (Criteria) this;
        }

        public Criteria andTotalamtNotEqualTo(BigDecimal value) {
            addCriterion("totalAmt <>", value, "totalamt");
            return (Criteria) this;
        }

        public Criteria andTotalamtGreaterThan(BigDecimal value) {
            addCriterion("totalAmt >", value, "totalamt");
            return (Criteria) this;
        }

        public Criteria andTotalamtGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("totalAmt >=", value, "totalamt");
            return (Criteria) this;
        }

        public Criteria andTotalamtLessThan(BigDecimal value) {
            addCriterion("totalAmt <", value, "totalamt");
            return (Criteria) this;
        }

        public Criteria andTotalamtLessThanOrEqualTo(BigDecimal value) {
            addCriterion("totalAmt <=", value, "totalamt");
            return (Criteria) this;
        }

        public Criteria andTotalamtIn(List<BigDecimal> values) {
            addCriterion("totalAmt in", values, "totalamt");
            return (Criteria) this;
        }

        public Criteria andTotalamtNotIn(List<BigDecimal> values) {
            addCriterion("totalAmt not in", values, "totalamt");
            return (Criteria) this;
        }

        public Criteria andTotalamtBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("totalAmt between", value1, value2, "totalamt");
            return (Criteria) this;
        }

        public Criteria andTotalamtNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("totalAmt not between", value1, value2, "totalamt");
            return (Criteria) this;
        }

        public Criteria andOrdidIsNull() {
            addCriterion("ordID is null");
            return (Criteria) this;
        }

        public Criteria andOrdidIsNotNull() {
            addCriterion("ordID is not null");
            return (Criteria) this;
        }

        public Criteria andOrdidEqualTo(Long value) {
            addCriterion("ordID =", value, "ordid");
            return (Criteria) this;
        }

        public Criteria andOrdidNotEqualTo(Long value) {
            addCriterion("ordID <>", value, "ordid");
            return (Criteria) this;
        }

        public Criteria andOrdidGreaterThan(Long value) {
            addCriterion("ordID >", value, "ordid");
            return (Criteria) this;
        }

        public Criteria andOrdidGreaterThanOrEqualTo(Long value) {
            addCriterion("ordID >=", value, "ordid");
            return (Criteria) this;
        }

        public Criteria andOrdidLessThan(Long value) {
            addCriterion("ordID <", value, "ordid");
            return (Criteria) this;
        }

        public Criteria andOrdidLessThanOrEqualTo(Long value) {
            addCriterion("ordID <=", value, "ordid");
            return (Criteria) this;
        }

        public Criteria andOrdidIn(List<Long> values) {
            addCriterion("ordID in", values, "ordid");
            return (Criteria) this;
        }

        public Criteria andOrdidNotIn(List<Long> values) {
            addCriterion("ordID not in", values, "ordid");
            return (Criteria) this;
        }

        public Criteria andOrdidBetween(Long value1, Long value2) {
            addCriterion("ordID between", value1, value2, "ordid");
            return (Criteria) this;
        }

        public Criteria andOrdidNotBetween(Long value1, Long value2) {
            addCriterion("ordID not between", value1, value2, "ordid");
            return (Criteria) this;
        }

        public Criteria andProdidIsNull() {
            addCriterion("prodID is null");
            return (Criteria) this;
        }

        public Criteria andProdidIsNotNull() {
            addCriterion("prodID is not null");
            return (Criteria) this;
        }

        public Criteria andProdidEqualTo(Long value) {
            addCriterion("prodID =", value, "prodid");
            return (Criteria) this;
        }

        public Criteria andProdidNotEqualTo(Long value) {
            addCriterion("prodID <>", value, "prodid");
            return (Criteria) this;
        }

        public Criteria andProdidGreaterThan(Long value) {
            addCriterion("prodID >", value, "prodid");
            return (Criteria) this;
        }

        public Criteria andProdidGreaterThanOrEqualTo(Long value) {
            addCriterion("prodID >=", value, "prodid");
            return (Criteria) this;
        }

        public Criteria andProdidLessThan(Long value) {
            addCriterion("prodID <", value, "prodid");
            return (Criteria) this;
        }

        public Criteria andProdidLessThanOrEqualTo(Long value) {
            addCriterion("prodID <=", value, "prodid");
            return (Criteria) this;
        }

        public Criteria andProdidIn(List<Long> values) {
            addCriterion("prodID in", values, "prodid");
            return (Criteria) this;
        }

        public Criteria andProdidNotIn(List<Long> values) {
            addCriterion("prodID not in", values, "prodid");
            return (Criteria) this;
        }

        public Criteria andProdidBetween(Long value1, Long value2) {
            addCriterion("prodID between", value1, value2, "prodid");
            return (Criteria) this;
        }

        public Criteria andProdidNotBetween(Long value1, Long value2) {
            addCriterion("prodID not between", value1, value2, "prodid");
            return (Criteria) this;
        }

        public Criteria andProdpriceIsNull() {
            addCriterion("prodPrice is null");
            return (Criteria) this;
        }

        public Criteria andProdpriceIsNotNull() {
            addCriterion("prodPrice is not null");
            return (Criteria) this;
        }

        public Criteria andProdpriceEqualTo(BigDecimal value) {
            addCriterion("prodPrice =", value, "prodprice");
            return (Criteria) this;
        }

        public Criteria andProdpriceNotEqualTo(BigDecimal value) {
            addCriterion("prodPrice <>", value, "prodprice");
            return (Criteria) this;
        }

        public Criteria andProdpriceGreaterThan(BigDecimal value) {
            addCriterion("prodPrice >", value, "prodprice");
            return (Criteria) this;
        }

        public Criteria andProdpriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("prodPrice >=", value, "prodprice");
            return (Criteria) this;
        }

        public Criteria andProdpriceLessThan(BigDecimal value) {
            addCriterion("prodPrice <", value, "prodprice");
            return (Criteria) this;
        }

        public Criteria andProdpriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("prodPrice <=", value, "prodprice");
            return (Criteria) this;
        }

        public Criteria andProdpriceIn(List<BigDecimal> values) {
            addCriterion("prodPrice in", values, "prodprice");
            return (Criteria) this;
        }

        public Criteria andProdpriceNotIn(List<BigDecimal> values) {
            addCriterion("prodPrice not in", values, "prodprice");
            return (Criteria) this;
        }

        public Criteria andProdpriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("prodPrice between", value1, value2, "prodprice");
            return (Criteria) this;
        }

        public Criteria andProdpriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("prodPrice not between", value1, value2, "prodprice");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNull() {
            addCriterion("username is null");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNotNull() {
            addCriterion("username is not null");
            return (Criteria) this;
        }

        public Criteria andUsernameEqualTo(String value) {
            addCriterion("username =", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotEqualTo(String value) {
            addCriterion("username <>", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThan(String value) {
            addCriterion("username >", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThanOrEqualTo(String value) {
            addCriterion("username >=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThan(String value) {
            addCriterion("username <", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThanOrEqualTo(String value) {
            addCriterion("username <=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLike(String value) {
            addCriterion("username like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotLike(String value) {
            addCriterion("username not like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameIn(List<String> values) {
            addCriterion("username in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotIn(List<String> values) {
            addCriterion("username not in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameBetween(String value1, String value2) {
            addCriterion("username between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotBetween(String value1, String value2) {
            addCriterion("username not between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andCartidIsNull() {
            addCriterion("cartID is null");
            return (Criteria) this;
        }

        public Criteria andCartidIsNotNull() {
            addCriterion("cartID is not null");
            return (Criteria) this;
        }

        public Criteria andCartidEqualTo(Long value) {
            addCriterion("cartID =", value, "cartid");
            return (Criteria) this;
        }

        public Criteria andCartidNotEqualTo(Long value) {
            addCriterion("cartID <>", value, "cartid");
            return (Criteria) this;
        }

        public Criteria andCartidGreaterThan(Long value) {
            addCriterion("cartID >", value, "cartid");
            return (Criteria) this;
        }

        public Criteria andCartidGreaterThanOrEqualTo(Long value) {
            addCriterion("cartID >=", value, "cartid");
            return (Criteria) this;
        }

        public Criteria andCartidLessThan(Long value) {
            addCriterion("cartID <", value, "cartid");
            return (Criteria) this;
        }

        public Criteria andCartidLessThanOrEqualTo(Long value) {
            addCriterion("cartID <=", value, "cartid");
            return (Criteria) this;
        }

        public Criteria andCartidIn(List<Long> values) {
            addCriterion("cartID in", values, "cartid");
            return (Criteria) this;
        }

        public Criteria andCartidNotIn(List<Long> values) {
            addCriterion("cartID not in", values, "cartid");
            return (Criteria) this;
        }

        public Criteria andCartidBetween(Long value1, Long value2) {
            addCriterion("cartID between", value1, value2, "cartid");
            return (Criteria) this;
        }

        public Criteria andCartidNotBetween(Long value1, Long value2) {
            addCriterion("cartID not between", value1, value2, "cartid");
            return (Criteria) this;
        }

        public Criteria andShpaddressIsNull() {
            addCriterion("shpAddress is null");
            return (Criteria) this;
        }

        public Criteria andShpaddressIsNotNull() {
            addCriterion("shpAddress is not null");
            return (Criteria) this;
        }

        public Criteria andShpaddressEqualTo(String value) {
            addCriterion("shpAddress =", value, "shpaddress");
            return (Criteria) this;
        }

        public Criteria andShpaddressNotEqualTo(String value) {
            addCriterion("shpAddress <>", value, "shpaddress");
            return (Criteria) this;
        }

        public Criteria andShpaddressGreaterThan(String value) {
            addCriterion("shpAddress >", value, "shpaddress");
            return (Criteria) this;
        }

        public Criteria andShpaddressGreaterThanOrEqualTo(String value) {
            addCriterion("shpAddress >=", value, "shpaddress");
            return (Criteria) this;
        }

        public Criteria andShpaddressLessThan(String value) {
            addCriterion("shpAddress <", value, "shpaddress");
            return (Criteria) this;
        }

        public Criteria andShpaddressLessThanOrEqualTo(String value) {
            addCriterion("shpAddress <=", value, "shpaddress");
            return (Criteria) this;
        }

        public Criteria andShpaddressLike(String value) {
            addCriterion("shpAddress like", value, "shpaddress");
            return (Criteria) this;
        }

        public Criteria andShpaddressNotLike(String value) {
            addCriterion("shpAddress not like", value, "shpaddress");
            return (Criteria) this;
        }

        public Criteria andShpaddressIn(List<String> values) {
            addCriterion("shpAddress in", values, "shpaddress");
            return (Criteria) this;
        }

        public Criteria andShpaddressNotIn(List<String> values) {
            addCriterion("shpAddress not in", values, "shpaddress");
            return (Criteria) this;
        }

        public Criteria andShpaddressBetween(String value1, String value2) {
            addCriterion("shpAddress between", value1, value2, "shpaddress");
            return (Criteria) this;
        }

        public Criteria andShpaddressNotBetween(String value1, String value2) {
            addCriterion("shpAddress not between", value1, value2, "shpaddress");
            return (Criteria) this;
        }

        public Criteria andPhonenumIsNull() {
            addCriterion("phoneNum is null");
            return (Criteria) this;
        }

        public Criteria andPhonenumIsNotNull() {
            addCriterion("phoneNum is not null");
            return (Criteria) this;
        }

        public Criteria andPhonenumEqualTo(String value) {
            addCriterion("phoneNum =", value, "phonenum");
            return (Criteria) this;
        }

        public Criteria andPhonenumNotEqualTo(String value) {
            addCriterion("phoneNum <>", value, "phonenum");
            return (Criteria) this;
        }

        public Criteria andPhonenumGreaterThan(String value) {
            addCriterion("phoneNum >", value, "phonenum");
            return (Criteria) this;
        }

        public Criteria andPhonenumGreaterThanOrEqualTo(String value) {
            addCriterion("phoneNum >=", value, "phonenum");
            return (Criteria) this;
        }

        public Criteria andPhonenumLessThan(String value) {
            addCriterion("phoneNum <", value, "phonenum");
            return (Criteria) this;
        }

        public Criteria andPhonenumLessThanOrEqualTo(String value) {
            addCriterion("phoneNum <=", value, "phonenum");
            return (Criteria) this;
        }

        public Criteria andPhonenumLike(String value) {
            addCriterion("phoneNum like", value, "phonenum");
            return (Criteria) this;
        }

        public Criteria andPhonenumNotLike(String value) {
            addCriterion("phoneNum not like", value, "phonenum");
            return (Criteria) this;
        }

        public Criteria andPhonenumIn(List<String> values) {
            addCriterion("phoneNum in", values, "phonenum");
            return (Criteria) this;
        }

        public Criteria andPhonenumNotIn(List<String> values) {
            addCriterion("phoneNum not in", values, "phonenum");
            return (Criteria) this;
        }

        public Criteria andPhonenumBetween(String value1, String value2) {
            addCriterion("phoneNum between", value1, value2, "phonenum");
            return (Criteria) this;
        }

        public Criteria andPhonenumNotBetween(String value1, String value2) {
            addCriterion("phoneNum not between", value1, value2, "phonenum");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table orderdetails
     *
     * @mbg.generated do_not_delete_during_merge Thu Jun 04 14:27:37 NPT 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table orderdetails
     *
     * @mbg.generated Thu Jun 04 14:27:37 NPT 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}