package com.ecommerce.OnlineShopping.domain;

import java.math.BigDecimal;
import java.util.Arrays;

public class Product {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.prodID
     *
     * @mbg.generated Mon Jun 01 17:53:15 NPT 2020
     */
    private Long prodid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.WishListID
     *
     * @mbg.generated Mon Jun 01 17:53:16 NPT 2020
     */
    private Long wishlistid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.cartID
     *
     * @mbg.generated Mon Jun 01 17:53:16 NPT 2020
     */
    private String cartid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.RatingsID
     *
     * @mbg.generated Mon Jun 01 17:53:16 NPT 2020
     */
    private Long ratingsid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.oderDetailsID
     *
     * @mbg.generated Mon Jun 01 17:53:16 NPT 2020
     */
    private Long oderdetailsid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.SalesID
     *
     * @mbg.generated Mon Jun 01 17:53:16 NPT 2020
     */
    private Long salesid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.prodName
     *
     * @mbg.generated Mon Jun 01 17:53:16 NPT 2020
     */
    private String prodname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.prodPrice
     *
     * @mbg.generated Mon Jun 01 17:53:16 NPT 2020
     */
    private BigDecimal prodprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.comment
     *
     * @mbg.generated Mon Jun 01 17:53:16 NPT 2020
     */
    private String comment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.stats
     *
     * @mbg.generated Mon Jun 01 17:53:16 NPT 2020
     */
    private String stats;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.Description
     *
     * @mbg.generated Mon Jun 01 17:53:16 NPT 2020
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.contentType
     *
     * @mbg.generated Mon Jun 01 17:53:16 NPT 2020
     */
    private String contenttype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.quantity
     *
     * @mbg.generated Mon Jun 01 17:53:16 NPT 2020
     */
    private Long quantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.prodImg
     *
     * @mbg.generated Mon Jun 01 17:53:16 NPT 2020
     */
    private byte[] prodimg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.prodID
     *
     * @return the value of product.prodID
     *
     * @mbg.generated Mon Jun 01 17:53:16 NPT 2020
     */
    public Long getProdid() {
        return prodid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.prodID
     *
     * @param prodid the value for product.prodID
     *
     * @mbg.generated Mon Jun 01 17:53:16 NPT 2020
     */
    public void setProdid(Long prodid) {
        this.prodid = prodid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.WishListID
     *
     * @return the value of product.WishListID
     *
     * @mbg.generated Mon Jun 01 17:53:16 NPT 2020
     */
    public Long getWishlistid() {
        return wishlistid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.WishListID
     *
     * @param wishlistid the value for product.WishListID
     *
     * @mbg.generated Mon Jun 01 17:53:16 NPT 2020
     */
    public void setWishlistid(Long wishlistid) {
        this.wishlistid = wishlistid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.cartID
     *
     * @return the value of product.cartID
     *
     * @mbg.generated Mon Jun 01 17:53:16 NPT 2020
     */
    public String getCartid() {
        return cartid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.cartID
     *
     * @param cartid the value for product.cartID
     *
     * @mbg.generated Mon Jun 01 17:53:16 NPT 2020
     */
    public void setCartid(String cartid) {
        this.cartid = cartid == null ? null : cartid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.RatingsID
     *
     * @return the value of product.RatingsID
     *
     * @mbg.generated Mon Jun 01 17:53:16 NPT 2020
     */
    public Long getRatingsid() {
        return ratingsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.RatingsID
     *
     * @param ratingsid the value for product.RatingsID
     *
     * @mbg.generated Mon Jun 01 17:53:16 NPT 2020
     */
    public void setRatingsid(Long ratingsid) {
        this.ratingsid = ratingsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.oderDetailsID
     *
     * @return the value of product.oderDetailsID
     *
     * @mbg.generated Mon Jun 01 17:53:16 NPT 2020
     */
    public Long getOderdetailsid() {
        return oderdetailsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.oderDetailsID
     *
     * @param oderdetailsid the value for product.oderDetailsID
     *
     * @mbg.generated Mon Jun 01 17:53:16 NPT 2020
     */
    public void setOderdetailsid(Long oderdetailsid) {
        this.oderdetailsid = oderdetailsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.SalesID
     *
     * @return the value of product.SalesID
     *
     * @mbg.generated Mon Jun 01 17:53:16 NPT 2020
     */
    public Long getSalesid() {
        return salesid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.SalesID
     *
     * @param salesid the value for product.SalesID
     *
     * @mbg.generated Mon Jun 01 17:53:16 NPT 2020
     */
    public void setSalesid(Long salesid) {
        this.salesid = salesid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.prodName
     *
     * @return the value of product.prodName
     *
     * @mbg.generated Mon Jun 01 17:53:16 NPT 2020
     */
    public String getProdname() {
        return prodname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.prodName
     *
     * @param prodname the value for product.prodName
     *
     * @mbg.generated Mon Jun 01 17:53:16 NPT 2020
     */
    public void setProdname(String prodname) {
        this.prodname = prodname == null ? null : prodname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.prodPrice
     *
     * @return the value of product.prodPrice
     *
     * @mbg.generated Mon Jun 01 17:53:16 NPT 2020
     */
    public BigDecimal getProdprice() {
        return prodprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.prodPrice
     *
     * @param prodprice the value for product.prodPrice
     *
     * @mbg.generated Mon Jun 01 17:53:16 NPT 2020
     */
    public void setProdprice(BigDecimal prodprice) {
        this.prodprice = prodprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.comment
     *
     * @return the value of product.comment
     *
     * @mbg.generated Mon Jun 01 17:53:16 NPT 2020
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.comment
     *
     * @param comment the value for product.comment
     *
     * @mbg.generated Mon Jun 01 17:53:16 NPT 2020
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.stats
     *
     * @return the value of product.stats
     *
     * @mbg.generated Mon Jun 01 17:53:16 NPT 2020
     */
    public String getStats() {
        return stats;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.stats
     *
     * @param stats the value for product.stats
     *
     * @mbg.generated Mon Jun 01 17:53:16 NPT 2020
     */
    public void setStats(String stats) {
        this.stats = stats == null ? null : stats.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.Description
     *
     * @return the value of product.Description
     *
     * @mbg.generated Mon Jun 01 17:53:16 NPT 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.Description
     *
     * @param description the value for product.Description
     *
     * @mbg.generated Mon Jun 01 17:53:16 NPT 2020
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.contentType
     *
     * @return the value of product.contentType
     *
     * @mbg.generated Mon Jun 01 17:53:16 NPT 2020
     */
    public String getContenttype() {
        return contenttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.contentType
     *
     * @param contenttype the value for product.contentType
     *
     * @mbg.generated Mon Jun 01 17:53:16 NPT 2020
     */
    public void setContenttype(String contenttype) {
        this.contenttype = contenttype == null ? null : contenttype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.quantity
     *
     * @return the value of product.quantity
     *
     * @mbg.generated Mon Jun 01 17:53:16 NPT 2020
     */
    public Long getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.quantity
     *
     * @param quantity the value for product.quantity
     *
     * @mbg.generated Mon Jun 01 17:53:16 NPT 2020
     */
    public void setQuantity(Long quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.prodImg
     *
     * @return the value of product.prodImg
     *
     * @mbg.generated Mon Jun 01 17:53:16 NPT 2020
     */
    public byte[] getProdimg() {
        return prodimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.prodImg
     *
     * @param prodimg the value for product.prodImg
     *
     * @mbg.generated Mon Jun 01 17:53:16 NPT 2020
     */
    public void setProdimg(byte[] prodimg) {
        this.prodimg = prodimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Mon Jun 01 17:53:16 NPT 2020
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Product other = (Product) that;
        return (this.getProdid() == null ? other.getProdid() == null : this.getProdid().equals(other.getProdid()))
            && (this.getWishlistid() == null ? other.getWishlistid() == null : this.getWishlistid().equals(other.getWishlistid()))
            && (this.getCartid() == null ? other.getCartid() == null : this.getCartid().equals(other.getCartid()))
            && (this.getRatingsid() == null ? other.getRatingsid() == null : this.getRatingsid().equals(other.getRatingsid()))
            && (this.getOderdetailsid() == null ? other.getOderdetailsid() == null : this.getOderdetailsid().equals(other.getOderdetailsid()))
            && (this.getSalesid() == null ? other.getSalesid() == null : this.getSalesid().equals(other.getSalesid()))
            && (this.getProdname() == null ? other.getProdname() == null : this.getProdname().equals(other.getProdname()))
            && (this.getProdprice() == null ? other.getProdprice() == null : this.getProdprice().equals(other.getProdprice()))
            && (this.getComment() == null ? other.getComment() == null : this.getComment().equals(other.getComment()))
            && (this.getStats() == null ? other.getStats() == null : this.getStats().equals(other.getStats()))
            && (this.getDescription() == null ? other.getDescription() == null : this.getDescription().equals(other.getDescription()))
            && (this.getContenttype() == null ? other.getContenttype() == null : this.getContenttype().equals(other.getContenttype()))
            && (this.getQuantity() == null ? other.getQuantity() == null : this.getQuantity().equals(other.getQuantity()))
            && (Arrays.equals(this.getProdimg(), other.getProdimg()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Mon Jun 01 17:53:16 NPT 2020
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getProdid() == null) ? 0 : getProdid().hashCode());
        result = prime * result + ((getWishlistid() == null) ? 0 : getWishlistid().hashCode());
        result = prime * result + ((getCartid() == null) ? 0 : getCartid().hashCode());
        result = prime * result + ((getRatingsid() == null) ? 0 : getRatingsid().hashCode());
        result = prime * result + ((getOderdetailsid() == null) ? 0 : getOderdetailsid().hashCode());
        result = prime * result + ((getSalesid() == null) ? 0 : getSalesid().hashCode());
        result = prime * result + ((getProdname() == null) ? 0 : getProdname().hashCode());
        result = prime * result + ((getProdprice() == null) ? 0 : getProdprice().hashCode());
        result = prime * result + ((getComment() == null) ? 0 : getComment().hashCode());
        result = prime * result + ((getStats() == null) ? 0 : getStats().hashCode());
        result = prime * result + ((getDescription() == null) ? 0 : getDescription().hashCode());
        result = prime * result + ((getContenttype() == null) ? 0 : getContenttype().hashCode());
        result = prime * result + ((getQuantity() == null) ? 0 : getQuantity().hashCode());
        result = prime * result + (Arrays.hashCode(getProdimg()));
        return result;
    }
}