package com.ecommerce.OnlineShopping.domain;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class ProductExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product
     *
     * @mbg.generated Mon Jun 01 17:53:15 NPT 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product
     *
     * @mbg.generated Mon Jun 01 17:53:15 NPT 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product
     *
     * @mbg.generated Mon Jun 01 17:53:15 NPT 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Mon Jun 01 17:53:15 NPT 2020
     */
    public ProductExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Mon Jun 01 17:53:15 NPT 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Mon Jun 01 17:53:15 NPT 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Mon Jun 01 17:53:15 NPT 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Mon Jun 01 17:53:15 NPT 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Mon Jun 01 17:53:15 NPT 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Mon Jun 01 17:53:15 NPT 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Mon Jun 01 17:53:15 NPT 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Mon Jun 01 17:53:15 NPT 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Mon Jun 01 17:53:15 NPT 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Mon Jun 01 17:53:15 NPT 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table product
     *
     * @mbg.generated Mon Jun 01 17:53:15 NPT 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andProdidIsNull() {
            addCriterion("prodID is null");
            return (Criteria) this;
        }

        public Criteria andProdidIsNotNull() {
            addCriterion("prodID is not null");
            return (Criteria) this;
        }

        public Criteria andProdidEqualTo(Long value) {
            addCriterion("prodID =", value, "prodid");
            return (Criteria) this;
        }

        public Criteria andProdidNotEqualTo(Long value) {
            addCriterion("prodID <>", value, "prodid");
            return (Criteria) this;
        }

        public Criteria andProdidGreaterThan(Long value) {
            addCriterion("prodID >", value, "prodid");
            return (Criteria) this;
        }

        public Criteria andProdidGreaterThanOrEqualTo(Long value) {
            addCriterion("prodID >=", value, "prodid");
            return (Criteria) this;
        }

        public Criteria andProdidLessThan(Long value) {
            addCriterion("prodID <", value, "prodid");
            return (Criteria) this;
        }

        public Criteria andProdidLessThanOrEqualTo(Long value) {
            addCriterion("prodID <=", value, "prodid");
            return (Criteria) this;
        }

        public Criteria andProdidIn(List<Long> values) {
            addCriterion("prodID in", values, "prodid");
            return (Criteria) this;
        }

        public Criteria andProdidNotIn(List<Long> values) {
            addCriterion("prodID not in", values, "prodid");
            return (Criteria) this;
        }

        public Criteria andProdidBetween(Long value1, Long value2) {
            addCriterion("prodID between", value1, value2, "prodid");
            return (Criteria) this;
        }

        public Criteria andProdidNotBetween(Long value1, Long value2) {
            addCriterion("prodID not between", value1, value2, "prodid");
            return (Criteria) this;
        }

        public Criteria andWishlistidIsNull() {
            addCriterion("WishListID is null");
            return (Criteria) this;
        }

        public Criteria andWishlistidIsNotNull() {
            addCriterion("WishListID is not null");
            return (Criteria) this;
        }

        public Criteria andWishlistidEqualTo(Long value) {
            addCriterion("WishListID =", value, "wishlistid");
            return (Criteria) this;
        }

        public Criteria andWishlistidNotEqualTo(Long value) {
            addCriterion("WishListID <>", value, "wishlistid");
            return (Criteria) this;
        }

        public Criteria andWishlistidGreaterThan(Long value) {
            addCriterion("WishListID >", value, "wishlistid");
            return (Criteria) this;
        }

        public Criteria andWishlistidGreaterThanOrEqualTo(Long value) {
            addCriterion("WishListID >=", value, "wishlistid");
            return (Criteria) this;
        }

        public Criteria andWishlistidLessThan(Long value) {
            addCriterion("WishListID <", value, "wishlistid");
            return (Criteria) this;
        }

        public Criteria andWishlistidLessThanOrEqualTo(Long value) {
            addCriterion("WishListID <=", value, "wishlistid");
            return (Criteria) this;
        }

        public Criteria andWishlistidIn(List<Long> values) {
            addCriterion("WishListID in", values, "wishlistid");
            return (Criteria) this;
        }

        public Criteria andWishlistidNotIn(List<Long> values) {
            addCriterion("WishListID not in", values, "wishlistid");
            return (Criteria) this;
        }

        public Criteria andWishlistidBetween(Long value1, Long value2) {
            addCriterion("WishListID between", value1, value2, "wishlistid");
            return (Criteria) this;
        }

        public Criteria andWishlistidNotBetween(Long value1, Long value2) {
            addCriterion("WishListID not between", value1, value2, "wishlistid");
            return (Criteria) this;
        }

        public Criteria andCartidIsNull() {
            addCriterion("cartID is null");
            return (Criteria) this;
        }

        public Criteria andCartidIsNotNull() {
            addCriterion("cartID is not null");
            return (Criteria) this;
        }

        public Criteria andCartidEqualTo(String value) {
            addCriterion("cartID =", value, "cartid");
            return (Criteria) this;
        }

        public Criteria andCartidNotEqualTo(String value) {
            addCriterion("cartID <>", value, "cartid");
            return (Criteria) this;
        }

        public Criteria andCartidGreaterThan(String value) {
            addCriterion("cartID >", value, "cartid");
            return (Criteria) this;
        }

        public Criteria andCartidGreaterThanOrEqualTo(String value) {
            addCriterion("cartID >=", value, "cartid");
            return (Criteria) this;
        }

        public Criteria andCartidLessThan(String value) {
            addCriterion("cartID <", value, "cartid");
            return (Criteria) this;
        }

        public Criteria andCartidLessThanOrEqualTo(String value) {
            addCriterion("cartID <=", value, "cartid");
            return (Criteria) this;
        }

        public Criteria andCartidLike(String value) {
            addCriterion("cartID like", value, "cartid");
            return (Criteria) this;
        }

        public Criteria andCartidNotLike(String value) {
            addCriterion("cartID not like", value, "cartid");
            return (Criteria) this;
        }

        public Criteria andCartidIn(List<String> values) {
            addCriterion("cartID in", values, "cartid");
            return (Criteria) this;
        }

        public Criteria andCartidNotIn(List<String> values) {
            addCriterion("cartID not in", values, "cartid");
            return (Criteria) this;
        }

        public Criteria andCartidBetween(String value1, String value2) {
            addCriterion("cartID between", value1, value2, "cartid");
            return (Criteria) this;
        }

        public Criteria andCartidNotBetween(String value1, String value2) {
            addCriterion("cartID not between", value1, value2, "cartid");
            return (Criteria) this;
        }

        public Criteria andRatingsidIsNull() {
            addCriterion("RatingsID is null");
            return (Criteria) this;
        }

        public Criteria andRatingsidIsNotNull() {
            addCriterion("RatingsID is not null");
            return (Criteria) this;
        }

        public Criteria andRatingsidEqualTo(Long value) {
            addCriterion("RatingsID =", value, "ratingsid");
            return (Criteria) this;
        }

        public Criteria andRatingsidNotEqualTo(Long value) {
            addCriterion("RatingsID <>", value, "ratingsid");
            return (Criteria) this;
        }

        public Criteria andRatingsidGreaterThan(Long value) {
            addCriterion("RatingsID >", value, "ratingsid");
            return (Criteria) this;
        }

        public Criteria andRatingsidGreaterThanOrEqualTo(Long value) {
            addCriterion("RatingsID >=", value, "ratingsid");
            return (Criteria) this;
        }

        public Criteria andRatingsidLessThan(Long value) {
            addCriterion("RatingsID <", value, "ratingsid");
            return (Criteria) this;
        }

        public Criteria andRatingsidLessThanOrEqualTo(Long value) {
            addCriterion("RatingsID <=", value, "ratingsid");
            return (Criteria) this;
        }

        public Criteria andRatingsidIn(List<Long> values) {
            addCriterion("RatingsID in", values, "ratingsid");
            return (Criteria) this;
        }

        public Criteria andRatingsidNotIn(List<Long> values) {
            addCriterion("RatingsID not in", values, "ratingsid");
            return (Criteria) this;
        }

        public Criteria andRatingsidBetween(Long value1, Long value2) {
            addCriterion("RatingsID between", value1, value2, "ratingsid");
            return (Criteria) this;
        }

        public Criteria andRatingsidNotBetween(Long value1, Long value2) {
            addCriterion("RatingsID not between", value1, value2, "ratingsid");
            return (Criteria) this;
        }

        public Criteria andOderdetailsidIsNull() {
            addCriterion("oderDetailsID is null");
            return (Criteria) this;
        }

        public Criteria andOderdetailsidIsNotNull() {
            addCriterion("oderDetailsID is not null");
            return (Criteria) this;
        }

        public Criteria andOderdetailsidEqualTo(Long value) {
            addCriterion("oderDetailsID =", value, "oderdetailsid");
            return (Criteria) this;
        }

        public Criteria andOderdetailsidNotEqualTo(Long value) {
            addCriterion("oderDetailsID <>", value, "oderdetailsid");
            return (Criteria) this;
        }

        public Criteria andOderdetailsidGreaterThan(Long value) {
            addCriterion("oderDetailsID >", value, "oderdetailsid");
            return (Criteria) this;
        }

        public Criteria andOderdetailsidGreaterThanOrEqualTo(Long value) {
            addCriterion("oderDetailsID >=", value, "oderdetailsid");
            return (Criteria) this;
        }

        public Criteria andOderdetailsidLessThan(Long value) {
            addCriterion("oderDetailsID <", value, "oderdetailsid");
            return (Criteria) this;
        }

        public Criteria andOderdetailsidLessThanOrEqualTo(Long value) {
            addCriterion("oderDetailsID <=", value, "oderdetailsid");
            return (Criteria) this;
        }

        public Criteria andOderdetailsidIn(List<Long> values) {
            addCriterion("oderDetailsID in", values, "oderdetailsid");
            return (Criteria) this;
        }

        public Criteria andOderdetailsidNotIn(List<Long> values) {
            addCriterion("oderDetailsID not in", values, "oderdetailsid");
            return (Criteria) this;
        }

        public Criteria andOderdetailsidBetween(Long value1, Long value2) {
            addCriterion("oderDetailsID between", value1, value2, "oderdetailsid");
            return (Criteria) this;
        }

        public Criteria andOderdetailsidNotBetween(Long value1, Long value2) {
            addCriterion("oderDetailsID not between", value1, value2, "oderdetailsid");
            return (Criteria) this;
        }

        public Criteria andSalesidIsNull() {
            addCriterion("SalesID is null");
            return (Criteria) this;
        }

        public Criteria andSalesidIsNotNull() {
            addCriterion("SalesID is not null");
            return (Criteria) this;
        }

        public Criteria andSalesidEqualTo(Long value) {
            addCriterion("SalesID =", value, "salesid");
            return (Criteria) this;
        }

        public Criteria andSalesidNotEqualTo(Long value) {
            addCriterion("SalesID <>", value, "salesid");
            return (Criteria) this;
        }

        public Criteria andSalesidGreaterThan(Long value) {
            addCriterion("SalesID >", value, "salesid");
            return (Criteria) this;
        }

        public Criteria andSalesidGreaterThanOrEqualTo(Long value) {
            addCriterion("SalesID >=", value, "salesid");
            return (Criteria) this;
        }

        public Criteria andSalesidLessThan(Long value) {
            addCriterion("SalesID <", value, "salesid");
            return (Criteria) this;
        }

        public Criteria andSalesidLessThanOrEqualTo(Long value) {
            addCriterion("SalesID <=", value, "salesid");
            return (Criteria) this;
        }

        public Criteria andSalesidIn(List<Long> values) {
            addCriterion("SalesID in", values, "salesid");
            return (Criteria) this;
        }

        public Criteria andSalesidNotIn(List<Long> values) {
            addCriterion("SalesID not in", values, "salesid");
            return (Criteria) this;
        }

        public Criteria andSalesidBetween(Long value1, Long value2) {
            addCriterion("SalesID between", value1, value2, "salesid");
            return (Criteria) this;
        }

        public Criteria andSalesidNotBetween(Long value1, Long value2) {
            addCriterion("SalesID not between", value1, value2, "salesid");
            return (Criteria) this;
        }

        public Criteria andProdnameIsNull() {
            addCriterion("prodName is null");
            return (Criteria) this;
        }

        public Criteria andProdnameIsNotNull() {
            addCriterion("prodName is not null");
            return (Criteria) this;
        }

        public Criteria andProdnameEqualTo(String value) {
            addCriterion("prodName =", value, "prodname");
            return (Criteria) this;
        }

        public Criteria andProdnameNotEqualTo(String value) {
            addCriterion("prodName <>", value, "prodname");
            return (Criteria) this;
        }

        public Criteria andProdnameGreaterThan(String value) {
            addCriterion("prodName >", value, "prodname");
            return (Criteria) this;
        }

        public Criteria andProdnameGreaterThanOrEqualTo(String value) {
            addCriterion("prodName >=", value, "prodname");
            return (Criteria) this;
        }

        public Criteria andProdnameLessThan(String value) {
            addCriterion("prodName <", value, "prodname");
            return (Criteria) this;
        }

        public Criteria andProdnameLessThanOrEqualTo(String value) {
            addCriterion("prodName <=", value, "prodname");
            return (Criteria) this;
        }

        public Criteria andProdnameLike(String value) {
            addCriterion("prodName like", value, "prodname");
            return (Criteria) this;
        }

        public Criteria andProdnameNotLike(String value) {
            addCriterion("prodName not like", value, "prodname");
            return (Criteria) this;
        }

        public Criteria andProdnameIn(List<String> values) {
            addCriterion("prodName in", values, "prodname");
            return (Criteria) this;
        }

        public Criteria andProdnameNotIn(List<String> values) {
            addCriterion("prodName not in", values, "prodname");
            return (Criteria) this;
        }

        public Criteria andProdnameBetween(String value1, String value2) {
            addCriterion("prodName between", value1, value2, "prodname");
            return (Criteria) this;
        }

        public Criteria andProdnameNotBetween(String value1, String value2) {
            addCriterion("prodName not between", value1, value2, "prodname");
            return (Criteria) this;
        }

        public Criteria andProdpriceIsNull() {
            addCriterion("prodPrice is null");
            return (Criteria) this;
        }

        public Criteria andProdpriceIsNotNull() {
            addCriterion("prodPrice is not null");
            return (Criteria) this;
        }

        public Criteria andProdpriceEqualTo(BigDecimal value) {
            addCriterion("prodPrice =", value, "prodprice");
            return (Criteria) this;
        }

        public Criteria andProdpriceNotEqualTo(BigDecimal value) {
            addCriterion("prodPrice <>", value, "prodprice");
            return (Criteria) this;
        }

        public Criteria andProdpriceGreaterThan(BigDecimal value) {
            addCriterion("prodPrice >", value, "prodprice");
            return (Criteria) this;
        }

        public Criteria andProdpriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("prodPrice >=", value, "prodprice");
            return (Criteria) this;
        }

        public Criteria andProdpriceLessThan(BigDecimal value) {
            addCriterion("prodPrice <", value, "prodprice");
            return (Criteria) this;
        }

        public Criteria andProdpriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("prodPrice <=", value, "prodprice");
            return (Criteria) this;
        }

        public Criteria andProdpriceIn(List<BigDecimal> values) {
            addCriterion("prodPrice in", values, "prodprice");
            return (Criteria) this;
        }

        public Criteria andProdpriceNotIn(List<BigDecimal> values) {
            addCriterion("prodPrice not in", values, "prodprice");
            return (Criteria) this;
        }

        public Criteria andProdpriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("prodPrice between", value1, value2, "prodprice");
            return (Criteria) this;
        }

        public Criteria andProdpriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("prodPrice not between", value1, value2, "prodprice");
            return (Criteria) this;
        }

        public Criteria andCommentIsNull() {
            addCriterion("comment is null");
            return (Criteria) this;
        }

        public Criteria andCommentIsNotNull() {
            addCriterion("comment is not null");
            return (Criteria) this;
        }

        public Criteria andCommentEqualTo(String value) {
            addCriterion("comment =", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotEqualTo(String value) {
            addCriterion("comment <>", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentGreaterThan(String value) {
            addCriterion("comment >", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentGreaterThanOrEqualTo(String value) {
            addCriterion("comment >=", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentLessThan(String value) {
            addCriterion("comment <", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentLessThanOrEqualTo(String value) {
            addCriterion("comment <=", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentLike(String value) {
            addCriterion("comment like", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotLike(String value) {
            addCriterion("comment not like", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentIn(List<String> values) {
            addCriterion("comment in", values, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotIn(List<String> values) {
            addCriterion("comment not in", values, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentBetween(String value1, String value2) {
            addCriterion("comment between", value1, value2, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotBetween(String value1, String value2) {
            addCriterion("comment not between", value1, value2, "comment");
            return (Criteria) this;
        }

        public Criteria andStatsIsNull() {
            addCriterion("stats is null");
            return (Criteria) this;
        }

        public Criteria andStatsIsNotNull() {
            addCriterion("stats is not null");
            return (Criteria) this;
        }

        public Criteria andStatsEqualTo(String value) {
            addCriterion("stats =", value, "stats");
            return (Criteria) this;
        }

        public Criteria andStatsNotEqualTo(String value) {
            addCriterion("stats <>", value, "stats");
            return (Criteria) this;
        }

        public Criteria andStatsGreaterThan(String value) {
            addCriterion("stats >", value, "stats");
            return (Criteria) this;
        }

        public Criteria andStatsGreaterThanOrEqualTo(String value) {
            addCriterion("stats >=", value, "stats");
            return (Criteria) this;
        }

        public Criteria andStatsLessThan(String value) {
            addCriterion("stats <", value, "stats");
            return (Criteria) this;
        }

        public Criteria andStatsLessThanOrEqualTo(String value) {
            addCriterion("stats <=", value, "stats");
            return (Criteria) this;
        }

        public Criteria andStatsLike(String value) {
            addCriterion("stats like", value, "stats");
            return (Criteria) this;
        }

        public Criteria andStatsNotLike(String value) {
            addCriterion("stats not like", value, "stats");
            return (Criteria) this;
        }

        public Criteria andStatsIn(List<String> values) {
            addCriterion("stats in", values, "stats");
            return (Criteria) this;
        }

        public Criteria andStatsNotIn(List<String> values) {
            addCriterion("stats not in", values, "stats");
            return (Criteria) this;
        }

        public Criteria andStatsBetween(String value1, String value2) {
            addCriterion("stats between", value1, value2, "stats");
            return (Criteria) this;
        }

        public Criteria andStatsNotBetween(String value1, String value2) {
            addCriterion("stats not between", value1, value2, "stats");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("Description is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("Description is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("Description =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("Description <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("Description >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("Description >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("Description <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("Description <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("Description like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("Description not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("Description in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("Description not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("Description between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("Description not between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andContenttypeIsNull() {
            addCriterion("contentType is null");
            return (Criteria) this;
        }

        public Criteria andContenttypeIsNotNull() {
            addCriterion("contentType is not null");
            return (Criteria) this;
        }

        public Criteria andContenttypeEqualTo(String value) {
            addCriterion("contentType =", value, "contenttype");
            return (Criteria) this;
        }

        public Criteria andContenttypeNotEqualTo(String value) {
            addCriterion("contentType <>", value, "contenttype");
            return (Criteria) this;
        }

        public Criteria andContenttypeGreaterThan(String value) {
            addCriterion("contentType >", value, "contenttype");
            return (Criteria) this;
        }

        public Criteria andContenttypeGreaterThanOrEqualTo(String value) {
            addCriterion("contentType >=", value, "contenttype");
            return (Criteria) this;
        }

        public Criteria andContenttypeLessThan(String value) {
            addCriterion("contentType <", value, "contenttype");
            return (Criteria) this;
        }

        public Criteria andContenttypeLessThanOrEqualTo(String value) {
            addCriterion("contentType <=", value, "contenttype");
            return (Criteria) this;
        }

        public Criteria andContenttypeLike(String value) {
            addCriterion("contentType like", value, "contenttype");
            return (Criteria) this;
        }

        public Criteria andContenttypeNotLike(String value) {
            addCriterion("contentType not like", value, "contenttype");
            return (Criteria) this;
        }

        public Criteria andContenttypeIn(List<String> values) {
            addCriterion("contentType in", values, "contenttype");
            return (Criteria) this;
        }

        public Criteria andContenttypeNotIn(List<String> values) {
            addCriterion("contentType not in", values, "contenttype");
            return (Criteria) this;
        }

        public Criteria andContenttypeBetween(String value1, String value2) {
            addCriterion("contentType between", value1, value2, "contenttype");
            return (Criteria) this;
        }

        public Criteria andContenttypeNotBetween(String value1, String value2) {
            addCriterion("contentType not between", value1, value2, "contenttype");
            return (Criteria) this;
        }

        public Criteria andQuantityIsNull() {
            addCriterion("quantity is null");
            return (Criteria) this;
        }

        public Criteria andQuantityIsNotNull() {
            addCriterion("quantity is not null");
            return (Criteria) this;
        }

        public Criteria andQuantityEqualTo(Long value) {
            addCriterion("quantity =", value, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityNotEqualTo(Long value) {
            addCriterion("quantity <>", value, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityGreaterThan(Long value) {
            addCriterion("quantity >", value, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityGreaterThanOrEqualTo(Long value) {
            addCriterion("quantity >=", value, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityLessThan(Long value) {
            addCriterion("quantity <", value, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityLessThanOrEqualTo(Long value) {
            addCriterion("quantity <=", value, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityIn(List<Long> values) {
            addCriterion("quantity in", values, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityNotIn(List<Long> values) {
            addCriterion("quantity not in", values, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityBetween(Long value1, Long value2) {
            addCriterion("quantity between", value1, value2, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityNotBetween(Long value1, Long value2) {
            addCriterion("quantity not between", value1, value2, "quantity");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table product
     *
     * @mbg.generated do_not_delete_during_merge Mon Jun 01 17:53:15 NPT 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table product
     *
     * @mbg.generated Mon Jun 01 17:53:15 NPT 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}