package com.ecommerce.OnlineShopping.domain;

public class Rating {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rating.RatingsID
     *
     * @mbg.generated Mon May 25 10:16:09 NPT 2020
     */
    private Long ratingsid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rating.ratingPoint
     *
     * @mbg.generated Mon May 25 10:16:09 NPT 2020
     */
    private Integer ratingpoint;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rating.prodID
     *
     * @mbg.generated Mon May 25 10:16:09 NPT 2020
     */
    private Long prodid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rating.RatingsID
     *
     * @return the value of rating.RatingsID
     *
     * @mbg.generated Mon May 25 10:16:09 NPT 2020
     */
    public Long getRatingsid() {
        return ratingsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rating.RatingsID
     *
     * @param ratingsid the value for rating.RatingsID
     *
     * @mbg.generated Mon May 25 10:16:09 NPT 2020
     */
    public void setRatingsid(Long ratingsid) {
        this.ratingsid = ratingsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rating.ratingPoint
     *
     * @return the value of rating.ratingPoint
     *
     * @mbg.generated Mon May 25 10:16:09 NPT 2020
     */
    public Integer getRatingpoint() {
        return ratingpoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rating.ratingPoint
     *
     * @param ratingpoint the value for rating.ratingPoint
     *
     * @mbg.generated Mon May 25 10:16:09 NPT 2020
     */
    public void setRatingpoint(Integer ratingpoint) {
        this.ratingpoint = ratingpoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rating.prodID
     *
     * @return the value of rating.prodID
     *
     * @mbg.generated Mon May 25 10:16:09 NPT 2020
     */
    public Long getProdid() {
        return prodid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rating.prodID
     *
     * @param prodid the value for rating.prodID
     *
     * @mbg.generated Mon May 25 10:16:09 NPT 2020
     */
    public void setProdid(Long prodid) {
        this.prodid = prodid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rating
     *
     * @mbg.generated Mon May 25 10:16:09 NPT 2020
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Rating other = (Rating) that;
        return (this.getRatingsid() == null ? other.getRatingsid() == null : this.getRatingsid().equals(other.getRatingsid()))
            && (this.getRatingpoint() == null ? other.getRatingpoint() == null : this.getRatingpoint().equals(other.getRatingpoint()))
            && (this.getProdid() == null ? other.getProdid() == null : this.getProdid().equals(other.getProdid()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rating
     *
     * @mbg.generated Mon May 25 10:16:09 NPT 2020
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getRatingsid() == null) ? 0 : getRatingsid().hashCode());
        result = prime * result + ((getRatingpoint() == null) ? 0 : getRatingpoint().hashCode());
        result = prime * result + ((getProdid() == null) ? 0 : getProdid().hashCode());
        return result;
    }
}