package com.ecommerce.OnlineShopping.domain;

import java.math.BigDecimal;
import java.util.Date;

public class ShoppingCart {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shoppingcart.cartID
     *
     * @mbg.generated Tue Jun 02 22:36:50 NPT 2020
     */
    private Long cartid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shoppingcart.cartDate
     *
     * @mbg.generated Tue Jun 02 22:36:50 NPT 2020
     */
    private Date cartdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shoppingcart.cartQuant
     *
     * @mbg.generated Tue Jun 02 22:36:50 NPT 2020
     */
    private Integer cartquant;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shoppingcart.cartTotalprice
     *
     * @mbg.generated Tue Jun 02 22:36:50 NPT 2020
     */
    private BigDecimal carttotalprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shoppingcart.prodid
     *
     * @mbg.generated Tue Jun 02 22:36:50 NPT 2020
     */
    private Long prodid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shoppingcart.username
     *
     * @mbg.generated Tue Jun 02 22:36:50 NPT 2020
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shoppingcart.prodPrice
     *
     * @mbg.generated Tue Jun 02 22:36:50 NPT 2020
     */
    private BigDecimal prodprice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shoppingcart.cartID
     *
     * @return the value of shoppingcart.cartID
     *
     * @mbg.generated Tue Jun 02 22:36:50 NPT 2020
     */
    public Long getCartid() {
        return cartid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shoppingcart.cartID
     *
     * @param cartid the value for shoppingcart.cartID
     *
     * @mbg.generated Tue Jun 02 22:36:50 NPT 2020
     */
    public void setCartid(Long cartid) {
        this.cartid = cartid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shoppingcart.cartDate
     *
     * @return the value of shoppingcart.cartDate
     *
     * @mbg.generated Tue Jun 02 22:36:50 NPT 2020
     */
    public Date getCartdate() {
        return cartdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shoppingcart.cartDate
     *
     * @param cartdate the value for shoppingcart.cartDate
     *
     * @mbg.generated Tue Jun 02 22:36:50 NPT 2020
     */
    public void setCartdate(Date cartdate) {
        this.cartdate = cartdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shoppingcart.cartQuant
     *
     * @return the value of shoppingcart.cartQuant
     *
     * @mbg.generated Tue Jun 02 22:36:50 NPT 2020
     */
    public Integer getCartquant() {
        return cartquant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shoppingcart.cartQuant
     *
     * @param cartquant the value for shoppingcart.cartQuant
     *
     * @mbg.generated Tue Jun 02 22:36:50 NPT 2020
     */
    public void setCartquant(Integer cartquant) {
        this.cartquant = cartquant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shoppingcart.cartTotalprice
     *
     * @return the value of shoppingcart.cartTotalprice
     *
     * @mbg.generated Tue Jun 02 22:36:50 NPT 2020
     */
    public BigDecimal getCarttotalprice() {
        return carttotalprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shoppingcart.cartTotalprice
     *
     * @param carttotalprice the value for shoppingcart.cartTotalprice
     *
     * @mbg.generated Tue Jun 02 22:36:50 NPT 2020
     */
    public void setCarttotalprice(BigDecimal carttotalprice) {
        this.carttotalprice = carttotalprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shoppingcart.prodid
     *
     * @return the value of shoppingcart.prodid
     *
     * @mbg.generated Tue Jun 02 22:36:50 NPT 2020
     */
    public Long getProdid() {
        return prodid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shoppingcart.prodid
     *
     * @param prodid the value for shoppingcart.prodid
     *
     * @mbg.generated Tue Jun 02 22:36:50 NPT 2020
     */
    public void setProdid(Long prodid) {
        this.prodid = prodid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shoppingcart.username
     *
     * @return the value of shoppingcart.username
     *
     * @mbg.generated Tue Jun 02 22:36:50 NPT 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shoppingcart.username
     *
     * @param username the value for shoppingcart.username
     *
     * @mbg.generated Tue Jun 02 22:36:50 NPT 2020
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shoppingcart.prodPrice
     *
     * @return the value of shoppingcart.prodPrice
     *
     * @mbg.generated Tue Jun 02 22:36:50 NPT 2020
     */
    public BigDecimal getProdprice() {
        return prodprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shoppingcart.prodPrice
     *
     * @param prodprice the value for shoppingcart.prodPrice
     *
     * @mbg.generated Tue Jun 02 22:36:50 NPT 2020
     */
    public void setProdprice(BigDecimal prodprice) {
        this.prodprice = prodprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shoppingcart
     *
     * @mbg.generated Tue Jun 02 22:36:50 NPT 2020
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ShoppingCart other = (ShoppingCart) that;
        return (this.getCartid() == null ? other.getCartid() == null : this.getCartid().equals(other.getCartid()))
            && (this.getCartdate() == null ? other.getCartdate() == null : this.getCartdate().equals(other.getCartdate()))
            && (this.getCartquant() == null ? other.getCartquant() == null : this.getCartquant().equals(other.getCartquant()))
            && (this.getCarttotalprice() == null ? other.getCarttotalprice() == null : this.getCarttotalprice().equals(other.getCarttotalprice()))
            && (this.getProdid() == null ? other.getProdid() == null : this.getProdid().equals(other.getProdid()))
            && (this.getUsername() == null ? other.getUsername() == null : this.getUsername().equals(other.getUsername()))
            && (this.getProdprice() == null ? other.getProdprice() == null : this.getProdprice().equals(other.getProdprice()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shoppingcart
     *
     * @mbg.generated Tue Jun 02 22:36:50 NPT 2020
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getCartid() == null) ? 0 : getCartid().hashCode());
        result = prime * result + ((getCartdate() == null) ? 0 : getCartdate().hashCode());
        result = prime * result + ((getCartquant() == null) ? 0 : getCartquant().hashCode());
        result = prime * result + ((getCarttotalprice() == null) ? 0 : getCarttotalprice().hashCode());
        result = prime * result + ((getProdid() == null) ? 0 : getProdid().hashCode());
        result = prime * result + ((getUsername() == null) ? 0 : getUsername().hashCode());
        result = prime * result + ((getProdprice() == null) ? 0 : getProdprice().hashCode());
        return result;
    }
}