package com.ecommerce.OnlineShopping.domain;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class TopSalesExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table topsales
     *
     * @mbg.generated Mon Jun 01 15:18:33 NPT 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table topsales
     *
     * @mbg.generated Mon Jun 01 15:18:33 NPT 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table topsales
     *
     * @mbg.generated Mon Jun 01 15:18:33 NPT 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topsales
     *
     * @mbg.generated Mon Jun 01 15:18:33 NPT 2020
     */
    public TopSalesExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topsales
     *
     * @mbg.generated Mon Jun 01 15:18:33 NPT 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topsales
     *
     * @mbg.generated Mon Jun 01 15:18:33 NPT 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topsales
     *
     * @mbg.generated Mon Jun 01 15:18:33 NPT 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topsales
     *
     * @mbg.generated Mon Jun 01 15:18:33 NPT 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topsales
     *
     * @mbg.generated Mon Jun 01 15:18:33 NPT 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topsales
     *
     * @mbg.generated Mon Jun 01 15:18:33 NPT 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topsales
     *
     * @mbg.generated Mon Jun 01 15:18:33 NPT 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topsales
     *
     * @mbg.generated Mon Jun 01 15:18:33 NPT 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topsales
     *
     * @mbg.generated Mon Jun 01 15:18:33 NPT 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topsales
     *
     * @mbg.generated Mon Jun 01 15:18:33 NPT 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table topsales
     *
     * @mbg.generated Mon Jun 01 15:18:33 NPT 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSalesidIsNull() {
            addCriterion("SalesID is null");
            return (Criteria) this;
        }

        public Criteria andSalesidIsNotNull() {
            addCriterion("SalesID is not null");
            return (Criteria) this;
        }

        public Criteria andSalesidEqualTo(Long value) {
            addCriterion("SalesID =", value, "salesid");
            return (Criteria) this;
        }

        public Criteria andSalesidNotEqualTo(Long value) {
            addCriterion("SalesID <>", value, "salesid");
            return (Criteria) this;
        }

        public Criteria andSalesidGreaterThan(Long value) {
            addCriterion("SalesID >", value, "salesid");
            return (Criteria) this;
        }

        public Criteria andSalesidGreaterThanOrEqualTo(Long value) {
            addCriterion("SalesID >=", value, "salesid");
            return (Criteria) this;
        }

        public Criteria andSalesidLessThan(Long value) {
            addCriterion("SalesID <", value, "salesid");
            return (Criteria) this;
        }

        public Criteria andSalesidLessThanOrEqualTo(Long value) {
            addCriterion("SalesID <=", value, "salesid");
            return (Criteria) this;
        }

        public Criteria andSalesidIn(List<Long> values) {
            addCriterion("SalesID in", values, "salesid");
            return (Criteria) this;
        }

        public Criteria andSalesidNotIn(List<Long> values) {
            addCriterion("SalesID not in", values, "salesid");
            return (Criteria) this;
        }

        public Criteria andSalesidBetween(Long value1, Long value2) {
            addCriterion("SalesID between", value1, value2, "salesid");
            return (Criteria) this;
        }

        public Criteria andSalesidNotBetween(Long value1, Long value2) {
            addCriterion("SalesID not between", value1, value2, "salesid");
            return (Criteria) this;
        }

        public Criteria andOfferpriceIsNull() {
            addCriterion("offerPrice is null");
            return (Criteria) this;
        }

        public Criteria andOfferpriceIsNotNull() {
            addCriterion("offerPrice is not null");
            return (Criteria) this;
        }

        public Criteria andOfferpriceEqualTo(BigDecimal value) {
            addCriterion("offerPrice =", value, "offerprice");
            return (Criteria) this;
        }

        public Criteria andOfferpriceNotEqualTo(BigDecimal value) {
            addCriterion("offerPrice <>", value, "offerprice");
            return (Criteria) this;
        }

        public Criteria andOfferpriceGreaterThan(BigDecimal value) {
            addCriterion("offerPrice >", value, "offerprice");
            return (Criteria) this;
        }

        public Criteria andOfferpriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("offerPrice >=", value, "offerprice");
            return (Criteria) this;
        }

        public Criteria andOfferpriceLessThan(BigDecimal value) {
            addCriterion("offerPrice <", value, "offerprice");
            return (Criteria) this;
        }

        public Criteria andOfferpriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("offerPrice <=", value, "offerprice");
            return (Criteria) this;
        }

        public Criteria andOfferpriceIn(List<BigDecimal> values) {
            addCriterion("offerPrice in", values, "offerprice");
            return (Criteria) this;
        }

        public Criteria andOfferpriceNotIn(List<BigDecimal> values) {
            addCriterion("offerPrice not in", values, "offerprice");
            return (Criteria) this;
        }

        public Criteria andOfferpriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("offerPrice between", value1, value2, "offerprice");
            return (Criteria) this;
        }

        public Criteria andOfferpriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("offerPrice not between", value1, value2, "offerprice");
            return (Criteria) this;
        }

        public Criteria andSalesdescIsNull() {
            addCriterion("salesDesc is null");
            return (Criteria) this;
        }

        public Criteria andSalesdescIsNotNull() {
            addCriterion("salesDesc is not null");
            return (Criteria) this;
        }

        public Criteria andSalesdescEqualTo(String value) {
            addCriterion("salesDesc =", value, "salesdesc");
            return (Criteria) this;
        }

        public Criteria andSalesdescNotEqualTo(String value) {
            addCriterion("salesDesc <>", value, "salesdesc");
            return (Criteria) this;
        }

        public Criteria andSalesdescGreaterThan(String value) {
            addCriterion("salesDesc >", value, "salesdesc");
            return (Criteria) this;
        }

        public Criteria andSalesdescGreaterThanOrEqualTo(String value) {
            addCriterion("salesDesc >=", value, "salesdesc");
            return (Criteria) this;
        }

        public Criteria andSalesdescLessThan(String value) {
            addCriterion("salesDesc <", value, "salesdesc");
            return (Criteria) this;
        }

        public Criteria andSalesdescLessThanOrEqualTo(String value) {
            addCriterion("salesDesc <=", value, "salesdesc");
            return (Criteria) this;
        }

        public Criteria andSalesdescLike(String value) {
            addCriterion("salesDesc like", value, "salesdesc");
            return (Criteria) this;
        }

        public Criteria andSalesdescNotLike(String value) {
            addCriterion("salesDesc not like", value, "salesdesc");
            return (Criteria) this;
        }

        public Criteria andSalesdescIn(List<String> values) {
            addCriterion("salesDesc in", values, "salesdesc");
            return (Criteria) this;
        }

        public Criteria andSalesdescNotIn(List<String> values) {
            addCriterion("salesDesc not in", values, "salesdesc");
            return (Criteria) this;
        }

        public Criteria andSalesdescBetween(String value1, String value2) {
            addCriterion("salesDesc between", value1, value2, "salesdesc");
            return (Criteria) this;
        }

        public Criteria andSalesdescNotBetween(String value1, String value2) {
            addCriterion("salesDesc not between", value1, value2, "salesdesc");
            return (Criteria) this;
        }

        public Criteria andStartdateIsNull() {
            addCriterion("startDate is null");
            return (Criteria) this;
        }

        public Criteria andStartdateIsNotNull() {
            addCriterion("startDate is not null");
            return (Criteria) this;
        }

        public Criteria andStartdateEqualTo(String value) {
            addCriterion("startDate =", value, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateNotEqualTo(String value) {
            addCriterion("startDate <>", value, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateGreaterThan(String value) {
            addCriterion("startDate >", value, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateGreaterThanOrEqualTo(String value) {
            addCriterion("startDate >=", value, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateLessThan(String value) {
            addCriterion("startDate <", value, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateLessThanOrEqualTo(String value) {
            addCriterion("startDate <=", value, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateLike(String value) {
            addCriterion("startDate like", value, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateNotLike(String value) {
            addCriterion("startDate not like", value, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateIn(List<String> values) {
            addCriterion("startDate in", values, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateNotIn(List<String> values) {
            addCriterion("startDate not in", values, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateBetween(String value1, String value2) {
            addCriterion("startDate between", value1, value2, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateNotBetween(String value1, String value2) {
            addCriterion("startDate not between", value1, value2, "startdate");
            return (Criteria) this;
        }

        public Criteria andEnddateIsNull() {
            addCriterion("EndDate is null");
            return (Criteria) this;
        }

        public Criteria andEnddateIsNotNull() {
            addCriterion("EndDate is not null");
            return (Criteria) this;
        }

        public Criteria andEnddateEqualTo(String value) {
            addCriterion("EndDate =", value, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateNotEqualTo(String value) {
            addCriterion("EndDate <>", value, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateGreaterThan(String value) {
            addCriterion("EndDate >", value, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateGreaterThanOrEqualTo(String value) {
            addCriterion("EndDate >=", value, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateLessThan(String value) {
            addCriterion("EndDate <", value, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateLessThanOrEqualTo(String value) {
            addCriterion("EndDate <=", value, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateLike(String value) {
            addCriterion("EndDate like", value, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateNotLike(String value) {
            addCriterion("EndDate not like", value, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateIn(List<String> values) {
            addCriterion("EndDate in", values, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateNotIn(List<String> values) {
            addCriterion("EndDate not in", values, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateBetween(String value1, String value2) {
            addCriterion("EndDate between", value1, value2, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateNotBetween(String value1, String value2) {
            addCriterion("EndDate not between", value1, value2, "enddate");
            return (Criteria) this;
        }

        public Criteria andProdidIsNull() {
            addCriterion("prodID is null");
            return (Criteria) this;
        }

        public Criteria andProdidIsNotNull() {
            addCriterion("prodID is not null");
            return (Criteria) this;
        }

        public Criteria andProdidEqualTo(Long value) {
            addCriterion("prodID =", value, "prodid");
            return (Criteria) this;
        }

        public Criteria andProdidNotEqualTo(Long value) {
            addCriterion("prodID <>", value, "prodid");
            return (Criteria) this;
        }

        public Criteria andProdidGreaterThan(Long value) {
            addCriterion("prodID >", value, "prodid");
            return (Criteria) this;
        }

        public Criteria andProdidGreaterThanOrEqualTo(Long value) {
            addCriterion("prodID >=", value, "prodid");
            return (Criteria) this;
        }

        public Criteria andProdidLessThan(Long value) {
            addCriterion("prodID <", value, "prodid");
            return (Criteria) this;
        }

        public Criteria andProdidLessThanOrEqualTo(Long value) {
            addCriterion("prodID <=", value, "prodid");
            return (Criteria) this;
        }

        public Criteria andProdidIn(List<Long> values) {
            addCriterion("prodID in", values, "prodid");
            return (Criteria) this;
        }

        public Criteria andProdidNotIn(List<Long> values) {
            addCriterion("prodID not in", values, "prodid");
            return (Criteria) this;
        }

        public Criteria andProdidBetween(Long value1, Long value2) {
            addCriterion("prodID between", value1, value2, "prodid");
            return (Criteria) this;
        }

        public Criteria andProdidNotBetween(Long value1, Long value2) {
            addCriterion("prodID not between", value1, value2, "prodid");
            return (Criteria) this;
        }

        public Criteria andContenttypeIsNull() {
            addCriterion("contentType is null");
            return (Criteria) this;
        }

        public Criteria andContenttypeIsNotNull() {
            addCriterion("contentType is not null");
            return (Criteria) this;
        }

        public Criteria andContenttypeEqualTo(String value) {
            addCriterion("contentType =", value, "contenttype");
            return (Criteria) this;
        }

        public Criteria andContenttypeNotEqualTo(String value) {
            addCriterion("contentType <>", value, "contenttype");
            return (Criteria) this;
        }

        public Criteria andContenttypeGreaterThan(String value) {
            addCriterion("contentType >", value, "contenttype");
            return (Criteria) this;
        }

        public Criteria andContenttypeGreaterThanOrEqualTo(String value) {
            addCriterion("contentType >=", value, "contenttype");
            return (Criteria) this;
        }

        public Criteria andContenttypeLessThan(String value) {
            addCriterion("contentType <", value, "contenttype");
            return (Criteria) this;
        }

        public Criteria andContenttypeLessThanOrEqualTo(String value) {
            addCriterion("contentType <=", value, "contenttype");
            return (Criteria) this;
        }

        public Criteria andContenttypeLike(String value) {
            addCriterion("contentType like", value, "contenttype");
            return (Criteria) this;
        }

        public Criteria andContenttypeNotLike(String value) {
            addCriterion("contentType not like", value, "contenttype");
            return (Criteria) this;
        }

        public Criteria andContenttypeIn(List<String> values) {
            addCriterion("contentType in", values, "contenttype");
            return (Criteria) this;
        }

        public Criteria andContenttypeNotIn(List<String> values) {
            addCriterion("contentType not in", values, "contenttype");
            return (Criteria) this;
        }

        public Criteria andContenttypeBetween(String value1, String value2) {
            addCriterion("contentType between", value1, value2, "contenttype");
            return (Criteria) this;
        }

        public Criteria andContenttypeNotBetween(String value1, String value2) {
            addCriterion("contentType not between", value1, value2, "contenttype");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table topsales
     *
     * @mbg.generated do_not_delete_during_merge Mon Jun 01 15:18:33 NPT 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table topsales
     *
     * @mbg.generated Mon Jun 01 15:18:33 NPT 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}