package com.ecommerce.OnlineShopping.domain;

import java.math.BigDecimal;
import java.util.Arrays;

public class TopSales {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topsales.SalesID
     *
     * @mbg.generated Mon Jun 01 15:18:33 NPT 2020
     */
    private Long salesid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topsales.offerPrice
     *
     * @mbg.generated Mon Jun 01 15:18:33 NPT 2020
     */
    private BigDecimal offerprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topsales.salesDesc
     *
     * @mbg.generated Mon Jun 01 15:18:33 NPT 2020
     */
    private String salesdesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topsales.startDate
     *
     * @mbg.generated Mon Jun 01 15:18:33 NPT 2020
     */
    private String startdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topsales.EndDate
     *
     * @mbg.generated Mon Jun 01 15:18:33 NPT 2020
     */
    private String enddate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topsales.prodID
     *
     * @mbg.generated Mon Jun 01 15:18:33 NPT 2020
     */
    private Long prodid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topsales.contentType
     *
     * @mbg.generated Mon Jun 01 15:18:33 NPT 2020
     */
    private String contenttype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topsales.name
     *
     * @mbg.generated Mon Jun 01 15:18:33 NPT 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topsales.prodImg
     *
     * @mbg.generated Mon Jun 01 15:18:33 NPT 2020
     */
    private byte[] prodimg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topsales.SalesID
     *
     * @return the value of topsales.SalesID
     *
     * @mbg.generated Mon Jun 01 15:18:33 NPT 2020
     */
    public Long getSalesid() {
        return salesid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topsales.SalesID
     *
     * @param salesid the value for topsales.SalesID
     *
     * @mbg.generated Mon Jun 01 15:18:33 NPT 2020
     */
    public void setSalesid(Long salesid) {
        this.salesid = salesid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topsales.offerPrice
     *
     * @return the value of topsales.offerPrice
     *
     * @mbg.generated Mon Jun 01 15:18:33 NPT 2020
     */
    public BigDecimal getOfferprice() {
        return offerprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topsales.offerPrice
     *
     * @param offerprice the value for topsales.offerPrice
     *
     * @mbg.generated Mon Jun 01 15:18:33 NPT 2020
     */
    public void setOfferprice(BigDecimal offerprice) {
        this.offerprice = offerprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topsales.salesDesc
     *
     * @return the value of topsales.salesDesc
     *
     * @mbg.generated Mon Jun 01 15:18:33 NPT 2020
     */
    public String getSalesdesc() {
        return salesdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topsales.salesDesc
     *
     * @param salesdesc the value for topsales.salesDesc
     *
     * @mbg.generated Mon Jun 01 15:18:33 NPT 2020
     */
    public void setSalesdesc(String salesdesc) {
        this.salesdesc = salesdesc == null ? null : salesdesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topsales.startDate
     *
     * @return the value of topsales.startDate
     *
     * @mbg.generated Mon Jun 01 15:18:33 NPT 2020
     */
    public String getStartdate() {
        return startdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topsales.startDate
     *
     * @param startdate the value for topsales.startDate
     *
     * @mbg.generated Mon Jun 01 15:18:33 NPT 2020
     */
    public void setStartdate(String startdate) {
        this.startdate = startdate == null ? null : startdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topsales.EndDate
     *
     * @return the value of topsales.EndDate
     *
     * @mbg.generated Mon Jun 01 15:18:33 NPT 2020
     */
    public String getEnddate() {
        return enddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topsales.EndDate
     *
     * @param enddate the value for topsales.EndDate
     *
     * @mbg.generated Mon Jun 01 15:18:33 NPT 2020
     */
    public void setEnddate(String enddate) {
        this.enddate = enddate == null ? null : enddate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topsales.prodID
     *
     * @return the value of topsales.prodID
     *
     * @mbg.generated Mon Jun 01 15:18:33 NPT 2020
     */
    public Long getProdid() {
        return prodid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topsales.prodID
     *
     * @param prodid the value for topsales.prodID
     *
     * @mbg.generated Mon Jun 01 15:18:33 NPT 2020
     */
    public void setProdid(Long prodid) {
        this.prodid = prodid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topsales.contentType
     *
     * @return the value of topsales.contentType
     *
     * @mbg.generated Mon Jun 01 15:18:33 NPT 2020
     */
    public String getContenttype() {
        return contenttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topsales.contentType
     *
     * @param contenttype the value for topsales.contentType
     *
     * @mbg.generated Mon Jun 01 15:18:33 NPT 2020
     */
    public void setContenttype(String contenttype) {
        this.contenttype = contenttype == null ? null : contenttype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topsales.name
     *
     * @return the value of topsales.name
     *
     * @mbg.generated Mon Jun 01 15:18:33 NPT 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topsales.name
     *
     * @param name the value for topsales.name
     *
     * @mbg.generated Mon Jun 01 15:18:33 NPT 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topsales.prodImg
     *
     * @return the value of topsales.prodImg
     *
     * @mbg.generated Mon Jun 01 15:18:33 NPT 2020
     */
    public byte[] getProdimg() {
        return prodimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topsales.prodImg
     *
     * @param prodimg the value for topsales.prodImg
     *
     * @mbg.generated Mon Jun 01 15:18:33 NPT 2020
     */
    public void setProdimg(byte[] prodimg) {
        this.prodimg = prodimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topsales
     *
     * @mbg.generated Mon Jun 01 15:18:33 NPT 2020
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TopSales other = (TopSales) that;
        return (this.getSalesid() == null ? other.getSalesid() == null : this.getSalesid().equals(other.getSalesid()))
            && (this.getOfferprice() == null ? other.getOfferprice() == null : this.getOfferprice().equals(other.getOfferprice()))
            && (this.getSalesdesc() == null ? other.getSalesdesc() == null : this.getSalesdesc().equals(other.getSalesdesc()))
            && (this.getStartdate() == null ? other.getStartdate() == null : this.getStartdate().equals(other.getStartdate()))
            && (this.getEnddate() == null ? other.getEnddate() == null : this.getEnddate().equals(other.getEnddate()))
            && (this.getProdid() == null ? other.getProdid() == null : this.getProdid().equals(other.getProdid()))
            && (this.getContenttype() == null ? other.getContenttype() == null : this.getContenttype().equals(other.getContenttype()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (Arrays.equals(this.getProdimg(), other.getProdimg()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topsales
     *
     * @mbg.generated Mon Jun 01 15:18:33 NPT 2020
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getSalesid() == null) ? 0 : getSalesid().hashCode());
        result = prime * result + ((getOfferprice() == null) ? 0 : getOfferprice().hashCode());
        result = prime * result + ((getSalesdesc() == null) ? 0 : getSalesdesc().hashCode());
        result = prime * result + ((getStartdate() == null) ? 0 : getStartdate().hashCode());
        result = prime * result + ((getEnddate() == null) ? 0 : getEnddate().hashCode());
        result = prime * result + ((getProdid() == null) ? 0 : getProdid().hashCode());
        result = prime * result + ((getContenttype() == null) ? 0 : getContenttype().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + (Arrays.hashCode(getProdimg()));
        return result;
    }
}