package com.ecommerce.OnlineShopping.domain;

import java.util.Date;

public class WishList {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wishlist.WishListID
     *
     * @mbg.generated Tue Jun 02 00:27:09 NPT 2020
     */
    private Long wishlistid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wishlist.addDate
     *
     * @mbg.generated Tue Jun 02 00:27:09 NPT 2020
     */
    private Date adddate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wishlist.username
     *
     * @mbg.generated Tue Jun 02 00:27:09 NPT 2020
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wishlist.ProdID
     *
     * @mbg.generated Tue Jun 02 00:27:09 NPT 2020
     */
    private Long prodid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wishlist.SalesID
     *
     * @mbg.generated Tue Jun 02 00:27:09 NPT 2020
     */
    private Long salesid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wishlist.WishListID
     *
     * @return the value of wishlist.WishListID
     *
     * @mbg.generated Tue Jun 02 00:27:09 NPT 2020
     */
    public Long getWishlistid() {
        return wishlistid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wishlist.WishListID
     *
     * @param wishlistid the value for wishlist.WishListID
     *
     * @mbg.generated Tue Jun 02 00:27:09 NPT 2020
     */
    public void setWishlistid(Long wishlistid) {
        this.wishlistid = wishlistid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wishlist.addDate
     *
     * @return the value of wishlist.addDate
     *
     * @mbg.generated Tue Jun 02 00:27:09 NPT 2020
     */
    public Date getAdddate() {
        return adddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wishlist.addDate
     *
     * @param adddate the value for wishlist.addDate
     *
     * @mbg.generated Tue Jun 02 00:27:09 NPT 2020
     */
    public void setAdddate(Date adddate) {
        this.adddate = adddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wishlist.username
     *
     * @return the value of wishlist.username
     *
     * @mbg.generated Tue Jun 02 00:27:09 NPT 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wishlist.username
     *
     * @param username the value for wishlist.username
     *
     * @mbg.generated Tue Jun 02 00:27:09 NPT 2020
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wishlist.ProdID
     *
     * @return the value of wishlist.ProdID
     *
     * @mbg.generated Tue Jun 02 00:27:09 NPT 2020
     */
    public Long getProdid() {
        return prodid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wishlist.ProdID
     *
     * @param prodid the value for wishlist.ProdID
     *
     * @mbg.generated Tue Jun 02 00:27:09 NPT 2020
     */
    public void setProdid(Long prodid) {
        this.prodid = prodid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wishlist.SalesID
     *
     * @return the value of wishlist.SalesID
     *
     * @mbg.generated Tue Jun 02 00:27:09 NPT 2020
     */
    public Long getSalesid() {
        return salesid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wishlist.SalesID
     *
     * @param salesid the value for wishlist.SalesID
     *
     * @mbg.generated Tue Jun 02 00:27:09 NPT 2020
     */
    public void setSalesid(Long salesid) {
        this.salesid = salesid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wishlist
     *
     * @mbg.generated Tue Jun 02 00:27:09 NPT 2020
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        WishList other = (WishList) that;
        return (this.getWishlistid() == null ? other.getWishlistid() == null : this.getWishlistid().equals(other.getWishlistid()))
            && (this.getAdddate() == null ? other.getAdddate() == null : this.getAdddate().equals(other.getAdddate()))
            && (this.getUsername() == null ? other.getUsername() == null : this.getUsername().equals(other.getUsername()))
            && (this.getProdid() == null ? other.getProdid() == null : this.getProdid().equals(other.getProdid()))
            && (this.getSalesid() == null ? other.getSalesid() == null : this.getSalesid().equals(other.getSalesid()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wishlist
     *
     * @mbg.generated Tue Jun 02 00:27:09 NPT 2020
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getWishlistid() == null) ? 0 : getWishlistid().hashCode());
        result = prime * result + ((getAdddate() == null) ? 0 : getAdddate().hashCode());
        result = prime * result + ((getUsername() == null) ? 0 : getUsername().hashCode());
        result = prime * result + ((getProdid() == null) ? 0 : getProdid().hashCode());
        result = prime * result + ((getSalesid() == null) ? 0 : getSalesid().hashCode());
        return result;
    }
}